export const COLORS = {
  critique:       '#c4622d',
  archive:        '#4a7c59',
  construction:   '#3d5a8a',
  aesthetics:     '#7c5cbf',
  coordination:   '#2a8a7a',
  infrastructure: '#c07a28',
  epistemology:   '#3a6ea8',
  ontology:       '#5a3a8a',
  core:           '#1a1510',
}

// ─── VISION 2 ────────────────────────────────────────────────────────────────

export const VISION_2 = {
  nodes: [
    {
      id: 'open_machine',
      label: 'Open Machine',
      type: 'open_machine',
      cluster: 'core',
      radius: 28,
      summary: 'A research and practice collective synthesizing immanent philosophy with emerging technology.',
      whyItMatters: 'The Open Machine inhabits all three movements simultaneously: diagnosing transcendent control structures, recovering protocol underground archives, and building immanent technological infrastructure.',
      tags: ['research', 'collective', 'immanence', 'protocol'],
    },

    // Movement I: The Critique of Control
    {
      id: 'critique',
      label: 'The Critique of Control',
      type: 'core',
      cluster: 'critique',
      radius: 22,
      summary: 'Diagnosis of the metaphysical, institutional, and computational structures that constrain cognition, agency, and collective coordination.',
      whyItMatters: 'Understanding what we resist is as important as what we build. Critique maps the mechanisms of domination across five registers: cognitive warfare, institutional capture, ontological hierarchy, political economy, and infrastructure enclosure.',
      tags: ['critique', 'institutions', 'power', 'diagnosis'],
    },
    {
      id: 'cognitive_warfare',
      label: 'Cognitive Warfare',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'Surveillance capitalism · Algorithmic political media · Algorithmic social media · AI one-shotting / narrative compression · Psychological targeting architectures · Aesthetic conditioning as enclosure',
      whyItMatters: 'Stiegler: aesthetics as political capture — the organization of sensibility as governance; vibes as network control. Cognitive warfare names the systematic weaponization of attention and perception as a governance strategy.',
      tags: ['surveillance', 'media', 'attention', 'Stiegler'],
    },
    {
      id: 'institutional_mind',
      label: 'The Institutional Mind',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'Institutional mind-blindness · Bureaucratic epistemology · Institutional cognitive enclosure · Legibility regimes · Institutional capture of intelligence · Process fascism',
      whyItMatters: 'Process fascism is the cutting edge: institutions adopting rhizomatic, open, participatory forms as a new capture strategy — the co-optation of distributed aesthetics by centralized power.',
      tags: ['institutions', 'epistemology', 'capture', 'legibility'],
    },
    {
      id: 'ontologies_control',
      label: 'Ontologies of Control',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'Emanationist ontology · The Great Chain of Being as operating system · Anthropocentric intelligence models · The individualist subject as governance primitive · Representation as cognitive bottleneck · Ontological violence as foundation',
      whyItMatters: 'Patterson, Hartman, Afropessimism: domination operates at the level of being — structural violence as ontological rather than merely political. Challenging it requires ontological, not just political, work.',
      tags: ['ontology', 'power', 'philosophy', 'afropessimism'],
    },
    {
      id: 'political_economy_control',
      label: 'Political Economy of Control',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'The Moloch frame and its discontents · Institutional fetishism · Competitive coordination traps · Capture of the commons · Institutional extraction of undercapital',
      whyItMatters: 'The Moloch framing risks naturalizing competitive defection rather than interrogating its conditions. Institutional fetishism absorbs and neutralizes transformative energy by treating institutions as reform-proxies and status-objects.',
      tags: ['political-economy', 'Moloch', 'commons', 'coordination'],
    },
    {
      id: 'cognitive_infra_capture',
      label: 'Cognitive Infrastructure Capture',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'Platform governance · Cloud platform centralization · Data enclosure · Cognitive rent extraction · Immersive technology as control terrain (BCI, VR, AR)',
      whyItMatters: 'BCI, VR, and AR are contested protocol terrain: attention architecture optimized for capture. The counter-mapping project asks what it would mean to design these environments for cognitive sovereignty instead.',
      tags: ['platform', 'infrastructure', 'data', 'BCI'],
    },

    // Movement II: Investigation of the Archive
    {
      id: 'archive',
      label: 'Investigation of the Archive',
      type: 'core',
      cluster: 'archive',
      radius: 22,
      summary: 'Excavating historical, cultural, and philosophical examples of alternative coordination systems — protocol undergrounds, epistemic cultures, virtual economies, immanent philosophy, ecological intelligence, and governance experiments.',
      whyItMatters: 'The underground is an empirical archive. Communities facing legal pressure solved coordination problems institutions claim are unsolvable. Their protocols are recoverable and scalable.',
      tags: ['history', 'archive', 'counterculture', 'practice'],
    },
    {
      id: 'protocol_underground',
      label: 'The Protocol Underground',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Underground protocolization (legal pressure → formal protocol → pluralism) · CA LSD underground · UK Free Party movement · Bay Area S/M scene · Appropriate Technology movement · High agency · Consent culture · Scale aversion · Overgrounding · The Walkaway Test',
      whyItMatters: 'The intellectual core of the research program. Legal/social pressure drives protocolization, which drives anti-capture resilience and pluralism. Overgrounding is the specific method: making underground practices transmissible without institutionalizing them.',
      tags: ['protocol', 'history', 'coordination', 'underground'],
    },
    {
      id: 'underground_epistemic',
      label: 'Underground Epistemic Cultures',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Hermetic knowledge transmission · Scene-based trust architectures · Adversarial epistemics under legal pressure · Stigmergic knowledge accumulation',
      whyItMatters: 'Underground communities construct, protect, and transmit knowledge under conditions of legal pressure, infiltration risk, and institutional hostility — generating epistemic forms unavailable to legitimate institutions.',
      tags: ['epistemology', 'trust', 'knowledge', 'underground'],
    },
    {
      id: 'economies_virtual',
      label: 'Economies of the Virtual',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Undercapital (nondual potentiality as the ninth form of capital) · Mutualism and encounter-based exchange · Gift economy logics · Commons as economic form · Scale-free and intersubjective monies',
      whyItMatters: 'Not "alternative" economics but economics adequate to non-actualized, relational, and intensive forms of value — value that existing capital categories cannot capture.',
      tags: ['economics', 'virtual', 'commons', 'undercapital'],
    },
    {
      id: 'immanent_tradition',
      label: 'The Immanent Tradition',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Process philosophy (Whitehead, Bergson, Deleuze) · Feminist new materialisms (Barad, Haraway, Braidotti) · Neurophenomenology and enactivism (Varela, Maturana) · The Undercommons (Moten, Harney) · Neotechnics (Mumford)',
      whyItMatters: 'A lineage organized around immanence, process, and relation — the philosophical archive the research program draws on and extends. Mumford\'s third technological epoch as historical analogue for the current protocol moment.',
      tags: ['philosophy', 'immanence', 'process', 'lineage'],
    },
    {
      id: 'ecological_intelligence',
      label: 'Ecological Intelligence Traditions',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Indigenous ecological knowledge systems · Systems ecology · Biosemiotics (von Uexküll: Umwelt) · Morphogenetic biology (Levin: diverse intelligence, basal cognition) · Autopoiesis (Varela, Maturana) · Symbiogenesis (Margulis)',
      whyItMatters: 'Cooperation, not competition, is the primary driver of evolutionary complexity. These traditions provide the empirical and conceptual basis for designing with ecological intelligence rather than against it.',
      tags: ['ecology', 'intelligence', 'biology', 'indigenous'],
    },
    {
      id: 'underground_governance',
      label: 'Underground Governance Experiments',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Temporary autonomous zones · Autonomous zones in practice · Cooperative cultural institutions · Commons governance (Ostrom: IAD framework) · Ethereum localism (cosmo-local governance, DPANs, neighbourhood DAOs, MycoFi) · Council-DAOs',
      whyItMatters: 'Consciousness-raising circles, sound system collectives, maker spaces, and council-DAOs are live experimental governance sites — proving grounds for the institutional forms the research program proposes.',
      tags: ['governance', 'DAOs', 'commons', 'Ostrom'],
    },

    // Movement III: The Construction of Immanent Technology
    {
      id: 'construction',
      label: 'The Construction of Immanent Technology',
      type: 'core',
      cluster: 'construction',
      radius: 22,
      summary: 'Designing technologies that amplify distributed cognition and emergent coordination — across cognitive sovereignty, open protocols, cognitive ecology, extitutional infrastructure, and process-based economic design.',
      whyItMatters: 'Construction is not the opposite of critique but its completion. The three movements are sequential and mutually reinforcing.',
      tags: ['construction', 'design', 'technology', 'immanence'],
    },
    {
      id: 'immanent_criteria',
      label: 'Immanent Technology Criteria',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Distribute agency not passivity · Enable aesthetic co-creation · Affirm consent, resist coercive coordination · Provoke processual thinking · Open-protocolize practical insights · Design for memeticism · Formalization without standardization',
      whyItMatters: 'Normative anchors for the design program — not research topics but evaluative standards. Empirically derived from studying protocol undergrounds. Memeticism means designing for divergent reproduction and mutation, not brand integrity.',
      tags: ['criteria', 'evaluation', 'values', 'design'],
    },
    {
      id: 'cognitive_sovereignty',
      label: 'Cognitive Sovereignty',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Self-owned cognitive infrastructure · Personal data autonomy · Local AI systems · Sovereign information environments · Anti-manipulation architectures',
      whyItMatters: 'Not just defense against cognitive enclosure but positive cultivation of direct interface with reality — epistemic autonomy adequate to discriminate between diverse intelligences and interfaces.',
      tags: ['sovereignty', 'autonomy', 'AI', 'infrastructure'],
    },
    {
      id: 'open_protocol_design',
      label: 'Open Protocol Design',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Protocolized coordination · Permissionless coordination systems · Composable institutional primitives · Coordination protocol design · Forkability as structural principle · Decentralized publishing protocol',
      whyItMatters: 'Forkability is a health indicator and anti-capture mechanism. Community-owned, modular, open-access infrastructure for protocol circulation and archival. The capacity to fork is what separates open protocols from enclosed standards.',
      tags: ['protocol', 'design', 'permissionless', 'forkability'],
    },
    {
      id: 'cognitive_ecology',
      label: 'Cognitive Ecology',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Noöpunk (universe as nested cognitive assemblages; diverse intelligence as economic agent) · Distributed cognition systems (Hutchins) · Open-ended intelligence (Weinbaum/Veitas) · Plural intelligence economies · Basal cognition (Levin) · Biosemiotic interfaces',
      whyItMatters: 'Research and design of systems adequate to the full diversity of cognitive agents — human, non-human, collective, distributed, machinic. Open-ended intelligence is an alternative to coordination-maximalism.',
      tags: ['cognition', 'ecology', 'intelligence', 'Nopunk'],
    },
    {
      id: 'extitutional_infra',
      label: 'Extitutional Infrastructure',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Extitutional coordination systems · Protocol organizations · Guild structures · Commons-based governance · Substrate (the permissionless social field) · Hyperstitional egregores',
      whyItMatters: 'Small organizations that use institutional legibility strategically to protect open protocols without institutionalizing the protocols themselves. Council-DAOs facilitate rather than capture egregoric energy. The Walkaway Test applies.',
      tags: ['extitution', 'organization', 'protocol', 'governance'],
    },
    {
      id: 'process_economic_design',
      label: 'Process-Based Economic Design',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Undercapital (nondual potentiality; ninth form of capital) · Processual assets · Anexact entities (Deleuze-Guattari) · Value occlusion sites · Tensioncraft · Intent-centric architectures · Intersubjective contextual monies',
      whyItMatters: 'Vagabond technology: systems organized around declared intent rather than identity or permission. Intersubjective contextual monies encode context and relation rather than abstracting from them.',
      tags: ['economics', 'process', 'Deleuze', 'value'],
    },
    {
      id: 'posthuman_technogenesis',
      label: 'Posthuman Technogenesis',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Human–machine co-evolution · Cognitive assemblages · Synthetic-ecological systems · Hybrid agency architectures · Feral computing (Austin Wade Smith) · Agentic and LLM extitutions',
      whyItMatters: 'Feral computing: systems that go feral — self-organizing, context-adaptive, ungovernable by design. Open research question: can LLMs function as extitutional agents participating in protocol undergrounds?',
      tags: ['posthumanism', 'AI', 'computing', 'agency'],
    },
  ],

  edges: [
    // Open Machine → movement cores
    { source: 'open_machine', target: 'critique',     type: 'direct_influence',  weight: 2 },
    { source: 'open_machine', target: 'archive',      type: 'direct_influence',  weight: 2 },
    { source: 'open_machine', target: 'construction', type: 'direct_influence',  weight: 2 },

    // Movement I → sections
    { source: 'critique', target: 'cognitive_warfare',         type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'institutional_mind',        type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'ontologies_control',        type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'political_economy_control', type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'cognitive_infra_capture',   type: 'direct_influence', weight: 1 },

    // Movement II → sections
    { source: 'archive', target: 'protocol_underground',  type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'underground_epistemic', type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'economies_virtual',     type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'immanent_tradition',    type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'ecological_intelligence', type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'underground_governance', type: 'direct_influence', weight: 1 },

    // Movement III → sections
    { source: 'construction', target: 'immanent_criteria',       type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'cognitive_sovereignty',   type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'open_protocol_design',    type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'cognitive_ecology',       type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'extitutional_infra',      type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'process_economic_design', type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'posthuman_technogenesis', type: 'direct_influence', weight: 1 },

    // Cross-movement spine
    { source: 'critique',  target: 'archive',      type: 'conceptual_affinity', weight: 2 },
    { source: 'archive',   target: 'construction', type: 'applied_extension',   weight: 2 },

    // Cross-concept connections (critique → construction)
    { source: 'cognitive_warfare',        target: 'cognitive_sovereignty',   type: 'applied_extension',   weight: 2 },
    { source: 'cognitive_infra_capture',  target: 'open_protocol_design',    type: 'applied_extension',   weight: 2 },
    { source: 'institutional_mind',       target: 'extitutional_infra',      type: 'applied_extension',   weight: 2 },
    { source: 'ontologies_control',       target: 'cognitive_ecology',       type: 'applied_extension',   weight: 2 },
    { source: 'political_economy_control', target: 'process_economic_design', type: 'applied_extension',  weight: 2 },

    // Cross-concept connections (archive → construction)
    { source: 'protocol_underground',    target: 'open_protocol_design',    type: 'applied_extension',   weight: 2 },
    { source: 'protocol_underground',    target: 'extitutional_infra',      type: 'conceptual_affinity', weight: 1 },
    { source: 'economies_virtual',       target: 'process_economic_design', type: 'applied_extension',   weight: 2 },
    { source: 'immanent_tradition',      target: 'cognitive_ecology',       type: 'conceptual_affinity', weight: 2 },
    { source: 'ecological_intelligence', target: 'cognitive_ecology',       type: 'applied_extension',   weight: 2 },
    { source: 'underground_governance',  target: 'extitutional_infra',      type: 'applied_extension',   weight: 2 },
    { source: 'underground_epistemic',   target: 'cognitive_sovereignty',   type: 'conceptual_affinity', weight: 1 },
    { source: 'immanent_tradition',      target: 'posthuman_technogenesis', type: 'conceptual_affinity', weight: 1 },
    { source: 'economies_virtual',       target: 'extitutional_infra',      type: 'conceptual_affinity', weight: 1 },
  ],
}

// ─── VISION 3 ────────────────────────────────────────────────────────────────

export const VISION_3 = {
  nodes: [
    {
      id: 'open_machine',
      label: 'Open Machine',
      type: 'open_machine',
      cluster: 'core',
      radius: 28,
      layer: 3,
      summary: 'A research and practice collective synthesizing immanent philosophy with emerging technology.',
      whyItMatters: 'The Open Machine inhabits all three movements simultaneously: diagnosing transcendent control structures, recovering protocol underground archives, and building immanent technological infrastructure.',
      tags: ['research', 'collective', 'immanence', 'protocol'],
    },

    // Layer 5 — Aesthetics & Phenomenology
    {
      id: 'layer5',
      label: 'Aesthetics & Phenomenology',
      type: 'core',
      cluster: 'aesthetics',
      radius: 22,
      layer: 5,
      summary: 'The fabric of collective sensory-cognitive life; how reality is felt and made as much as known.',
      whyItMatters: 'Aesthetics in the Stieglerian sense (aisthēsis) is the most fundamental layer — it shapes what can be perceived and experienced before any epistemology or coordination is possible.',
      tags: ['aesthetics', 'phenomenology', 'experience'],
    },
    {
      id: 'nopunk_l5',
      label: 'Noöpunk',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'The aesthetic-political movement seeing the universe as nested cognitive assemblages activating through art, music, computation, and ecology.',
      whyItMatters: 'Noöpunk is the felt practice of the entire stack — what living inside an immanent world looks and feels like.',
      tags: ['art', 'culture', 'cognition'],
    },
    {
      id: 'symbolic_commons',
      label: 'Symbolic Commons',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'Shared aesthetic and symbolic resources held in common — music, imagery, language, narrative — that enable collective sense-making outside market mediation.',
      whyItMatters: 'The symbolic commons is what cognitive enclosure destroys and what protocol undergrounds rebuild. It is the aesthetic infrastructure of community.',
      tags: ['commons', 'aesthetics', 'culture'],
    },
    {
      id: 'aisthesis',
      label: 'Aisthēsis',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'The pre-cognitive, bodily dimension of perception and sensory experience — what Stiegler identifies as the primary site of political-aesthetic contestation.',
      whyItMatters: 'Aisthēsis is why advertising and algorithmic media are more than annoyances — they restructure the perceptual substrate of collective life before thought begins.',
      tags: ['Stiegler', 'perception', 'politics'],
    },
    {
      id: 'technedelics_l5',
      label: 'Technedelics',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'Technologies and practices (psychedelics, VR, deep media) that enable encounter with radically foreign umwelts — alien sensory-cognitive worlds.',
      whyItMatters: 'Technedelics sit at the intersection of aesthetics and epistemology: they are the most radical form of perceptual expansion, testing the limits of what can be experienced and known.',
      tags: ['psychedelics', 'umwelt', 'experience'],
    },

    // Layer 4 — Coordination & Governance
    {
      id: 'layer4',
      label: 'Coordination & Governance',
      type: 'core',
      cluster: 'coordination',
      radius: 22,
      layer: 4,
      summary: 'How distributed agents act together without surrendering agency to a center — stigmergy, polycentric governance, consent culture, cosmo-local networks.',
      whyItMatters: 'Coordination is where ontology meets practice. The question is not whether to coordinate but on what terms — and with what relationship to diverse intelligences and open protocols.',
      tags: ['coordination', 'governance', 'collective'],
    },
    {
      id: 'cosmo_local_l4',
      label: 'Cosmo-Localism',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Heavy things local, light things global. Resilient bioregional production networked to shared knowledge commons.',
      whyItMatters: 'Cosmo-localism is the operational synthesis of the entire project — how to be rooted and connected without being isolated or homogenized.',
      tags: ['cosmo-localism', 'local', 'global'],
    },
    {
      id: 'stigmergy',
      label: 'Stigmergy',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Swarm coordination without central planning — agents signal through environmental modification, enabling positive-sum feedback loops (ants, Wikipedia, Burning Man).',
      whyItMatters: 'Stigmergy proves that complex collective coordination doesn\'t require hierarchy or central authority. It is the coordination mechanism of the protocol underground.',
      tags: ['swarm', 'emergence', 'coordination'],
    },
    {
      id: 'polycentric',
      label: 'Polycentric Governance',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Multiple overlapping scales of governance, each handling what is appropriate to its level — Ostrom\'s principle of subsidiarity applied to information and resource commons.',
      whyItMatters: 'Polycentric governance is how cosmo-localism gets operationalized institutionally: neither global monoculture nor local fragmentation but nested, overlapping jurisdictions.',
      tags: ['Ostrom', 'commons', 'governance'],
    },
    {
      id: 'consent_culture',
      label: 'Consent Culture',
      type: 'tradition',
      cluster: 'coordination',
      radius: 17,
      layer: 4,
      summary: 'The S/M community\'s development of explicit, ongoing, renegotiable consent as a full coordination protocol — now recoverable for broader social design.',
      whyItMatters: 'Consent culture is the protocol underground\'s answer to how you coordinate intimately without coercion. It is a working proof of concept for affirmative consent as governance principle.',
      tags: ['consent', 'protocol', 'ethics', 'history'],
    },
    {
      id: 'semiotic_bridging',
      label: 'Semiotic Bridging',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Revealing underlying compatibility between diverse movements and frameworks by translating between their distinct vocabularies without demanding ideological unity.',
      whyItMatters: 'Semiotic bridging is how cosmo-local coalitions are built. It is the communicative practice that allows diverse communities to coordinate without standardizing.',
      tags: ['communication', 'translation', 'coalition'],
    },

    // Layer 3 — Infrastructure
    {
      id: 'layer3',
      label: 'Infrastructure',
      type: 'core',
      cluster: 'infrastructure',
      radius: 22,
      layer: 3,
      summary: 'The formal substrate that makes coordination legible without making it capturable — open protocols, cryptographic consensus, distributed compute.',
      whyItMatters: 'Infrastructure is the layer that either enables or forecloses all layers above it. Open infrastructure is the technical precondition for immanent governance and aesthetics.',
      tags: ['infrastructure', 'protocol', 'technical'],
    },
    {
      id: 'ethereum',
      label: 'Ethereum',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Ontologically agnostic distributed compute infrastructure — capable of treating diverse forms of intelligence and agency symmetrically, without reference to human sovereignty.',
      whyItMatters: 'Ethereum is posthuman infrastructure: it provides formalization without standardization, minimum viable consensus through mathematics rather than institutional authority.',
      tags: ['Ethereum', 'blockchain', 'posthumanism'],
    },
    {
      id: 'open_protocols',
      label: 'Open Protocols',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Memetic, empirical, anti-capture protocol design — reproducible, forkable, adaptable to local context without losing coherence.',
      whyItMatters: 'Open protocols are the formalization without standardization that allows underground practices to scale. They are the technical instantiation of the isomorphism thesis.',
      tags: ['protocol', 'open-source', 'design'],
    },
    {
      id: 'daos',
      label: 'DAOs',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Decentralized autonomous organizations: smart-contract-based coordination mechanisms that formalize governance without requiring institutional authority.',
      whyItMatters: 'DAOs are the organizational form corresponding to extitutional strategy — they use institutional legibility (legal wrappers) while remaining operationally committed to distributed governance.',
      tags: ['DAOs', 'governance', 'smart-contracts'],
    },
    {
      id: 'mycofi',
      label: 'MycoFi',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Fungal network models applied to distributed resource allocation — the mycelium as both metaphor and template for peer-to-peer economic coordination.',
      whyItMatters: 'MycoFi extends cosmo-localism into regenerative economics, proposing that resource flows can be organized according to ecological rather than market logics.',
      tags: ['ecology', 'economics', 'distributed'],
    },

    // Layer 2 — Epistemology & Cognition
    {
      id: 'layer2',
      label: 'Epistemology & Cognition',
      type: 'core',
      cluster: 'epistemology',
      radius: 22,
      layer: 2,
      summary: 'What counts as knowing, who counts as a knower, and who controls the conditions of perception — the contested layer of diverse intelligence and cognitive sovereignty.',
      whyItMatters: 'Epistemology is where the philosophical and the political converge: controlling how we know is controlling how we can act and what we can coordinate with.',
      tags: ['epistemology', 'cognition', 'sovereignty'],
    },
    {
      id: 'diverse_intel_l2',
      label: 'Diverse Intelligence',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Michael Levin\'s framework: intelligence as distributed across nested problem-solving systems — cells in metabolic space, organisms in physical space, collectives in social space.',
      whyItMatters: 'Diverse intelligence expands the roster of cognitive agents we can coordinate with, and provides the epistemological ground for posthumanist infrastructure design.',
      tags: ['Levin', 'intelligence', 'cognition'],
    },
    {
      id: 'cog_sovereignty_l2',
      label: 'Cognitive Sovereignty',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Freedom from institutional determination of thought and perception — the positive capacity to appraise and engage diverse intelligences from a position of epistemic autonomy.',
      whyItMatters: 'Cognitive sovereignty is the personal and collective counterpart to open protocol infrastructure: it is what free infrastructure enables and what cognitive enclosure destroys.',
      tags: ['sovereignty', 'autonomy', 'cognition'],
    },
    {
      id: 'umwelt',
      label: 'Umwelt',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Jakob von Uexküll\'s concept: each organism inhabits a unique perceptual world defined by its sensory apparatus and cognitive capacities. Encountering alien umwelts expands epistemic space.',
      whyItMatters: 'Umwelt thinking is the perceptual foundation of diverse intelligence: to recognize other minds, you must be able to conceive that other perceptual worlds exist and are real.',
      tags: ['umwelt', 'perception', 'biology'],
    },
    {
      id: 'dist_cognition',
      label: 'Distributed Cognition',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Edward Hutchins\' framework: cognitive processes extend beyond individual minds into socio-technical systems. Ships navigate, teams problem-solve, cities remember.',
      whyItMatters: 'Distributed cognition grounds the stigmergy claim: collective intelligence is not metaphorical but literally cognitive — the system knows things no individual knows.',
      tags: ['Hutchins', 'cognition', 'systems'],
    },
    {
      id: 'technedelics_l2',
      label: 'Technedelics (Epistemic)',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Psychedelics and radical media as epistemological tools: empirical access to alien umwelts, direct test of the limits of cognitive sovereignty.',
      whyItMatters: 'From the epistemological layer, technedelics are less about experience and more about what they prove: that other cognitive worlds are real and accessible, and that the sovereign observer is a construction.',
      tags: ['psychedelics', 'epistemology', 'umwelt'],
    },

    // Layer 1 — Ontology
    {
      id: 'layer1',
      label: 'Ontology',
      type: 'core',
      cluster: 'ontology',
      radius: 22,
      layer: 1,
      summary: 'What is real; what kinds of agency exist; what is the nature of creative emergence — the philosophical ground of the entire stack.',
      whyItMatters: 'Ontology is not the most abstract layer but the most fundamental. Every design decision about infrastructure, governance, and aesthetics encodes ontological assumptions. Making them explicit is the work of layer 1.',
      tags: ['ontology', 'philosophy', 'metaphysics'],
    },
    {
      id: 'immanence',
      label: 'Immanence',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Deleuzian concept: creative capacity arising from relational fields without central command. Power distributed within, not emanating from above. Against transcendence in all its forms.',
      whyItMatters: 'Immanence is the unifying philosophical principle of the entire project. It names what the three movements and five layers are all, in their different registers, trying to instantiate.',
      tags: ['Deleuze', 'immanence', 'philosophy'],
    },
    {
      id: 'the_virtual',
      label: 'The Virtual',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Deleuze\'s reading of Bergson: the virtual is real but not actual — the generative field of potentiality that animates material processes without being directly quantifiable.',
      whyItMatters: 'The virtual is why undercapital is real economics, why the underground matters, why aesthetic experience is productive. It names the dimension that institutional accounting cannot see.',
      tags: ['Deleuze', 'Bergson', 'virtual', 'potentiality'],
    },
    {
      id: 'undercapital_l1',
      label: 'Undercapital',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'The ontological claim behind the economic concept: that the virtual dimension is a real productive force, and that organizing to access it generates genuine value.',
      whyItMatters: 'Undercapital at the coordination layer is the claim that the felt sense of possibility is not epiphenomenal but causal — that presence, trust, and affective charge are primary economic facts.',
      tags: ['economics', 'virtual', 'coordination'],
    },
    {
      id: 'open_ended',
      label: 'Open-Ended Intelligence',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Weinbaum & Veitas: intelligence as distributed, self-reflexive, and without terminal state — the rejection of goal-optimization for open-ended adaptive becoming.',
      whyItMatters: 'Open-ended intelligence is the ontological basis for diverse intelligence: if intelligence has no fixed goal, it cannot be defined by its output but only by its processual character.',
      tags: ['intelligence', 'AI', 'becoming'],
    },
    {
      id: 'posthumanism',
      label: 'Posthumanism',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Rejection of the autonomous sovereign subject as the primary unit of moral and political consideration — distributed agency at all scales, from cells to collectives.',
      whyItMatters: 'Posthumanism is the ontological foundation for Ethereum\'s technical design (no reference to human sovereignty), for diverse intelligence research, and for bioregional governance.',
      tags: ['posthumanism', 'agency', 'subject'],
    },
  ],

  edges: [
    { source: 'open_machine',      target: 'layer5',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer4',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer3',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer2',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer1',            type: 'direct_influence',   weight: 2 },
    { source: 'layer5',            target: 'nopunk_l5',         type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'symbolic_commons',  type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'aisthesis',         type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'technedelics_l5',   type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'cosmo_local_l4',    type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'stigmergy',         type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'polycentric',       type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'consent_culture',   type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'semiotic_bridging', type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'ethereum',          type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'open_protocols',    type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'daos',              type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'mycofi',            type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'diverse_intel_l2',  type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'cog_sovereignty_l2', type: 'direct_influence',  weight: 1 },
    { source: 'layer2',            target: 'umwelt',            type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'dist_cognition',    type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'technedelics_l2',   type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'immanence',         type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'the_virtual',       type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'undercapital_l1',   type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'open_ended',        type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'posthumanism',      type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'layer2',            type: 'applied_extension',  weight: 3 },
    { source: 'layer2',            target: 'layer3',            type: 'applied_extension',  weight: 3 },
    { source: 'layer3',            target: 'layer4',            type: 'applied_extension',  weight: 3 },
    { source: 'layer4',            target: 'layer5',            type: 'applied_extension',  weight: 3 },
    { source: 'immanence',         target: 'diverse_intel_l2',  type: 'conceptual_affinity', weight: 2 },
    { source: 'the_virtual',       target: 'undercapital_l1',   type: 'conceptual_affinity', weight: 2 },
    { source: 'open_ended',        target: 'diverse_intel_l2',  type: 'conceptual_affinity', weight: 2 },
    { source: 'posthumanism',      target: 'ethereum',          type: 'applied_extension',  weight: 2 },
    { source: 'umwelt',            target: 'technedelics_l5',   type: 'conceptual_affinity', weight: 2 },
    { source: 'stigmergy',         target: 'open_protocols',    type: 'conceptual_affinity', weight: 2 },
    { source: 'consent_culture',   target: 'daos',              type: 'applied_extension',  weight: 2 },
    { source: 'cosmo_local_l4',    target: 'mycofi',            type: 'conceptual_affinity', weight: 1 },
    { source: 'aisthesis',         target: 'symbolic_commons',  type: 'conceptual_affinity', weight: 1 },
    { source: 'dist_cognition',    target: 'stigmergy',         type: 'conceptual_affinity', weight: 2 },
    { source: 'technedelics_l2',   target: 'technedelics_l5',   type: 'conceptual_affinity', weight: 1 },
  ],
}
