export const COLORS = {
  critique:       '#c4622d',
  archive:        '#4a7c59',
  construction:   '#3d5a8a',
  aesthetics:     '#7c5cbf',
  coordination:   '#2a8a7a',
  infrastructure: '#c07a28',
  epistemology:   '#3a6ea8',
  ontology:       '#5a3a8a',
  core:           '#1a1510',
}

// ─── VISION 2 ────────────────────────────────────────────────────────────────

export const VISION_2 = {
  nodes: [
    {
      id: 'open_machine',
      label: 'Open Machine',
      type: 'open_machine',
      cluster: 'core',
      radius: 28,
      summary: 'A research and practice collective synthesizing immanent philosophy, protocol underground history, and emergent technology — operating across all three movements simultaneously.',
      whyItMatters: 'The Open Machine occupies the intersection of critique, archive, and construction: diagnosing the mechanisms of control, excavating the protocol underground as an empirical archive, and building the overgrounding infrastructure that makes underground values transmissible without standardizing them.',
      tags: ['research', 'collective', 'immanence', 'protocol'],
    },

    // Movement I: The Critique of Control
    {
      id: 'critique',
      label: 'The Critique of Control',
      type: 'core',
      cluster: 'critique',
      radius: 22,
      summary: 'Control is the organizational mode — inherited from Emanationist cosmology — that constitutes power as emanating from an interior source, mystifying the relational and networked nature of all power. A Control organization is composed of a protocol and a ban: the mystified withholding of access to the relational elements that animate it.',
      whyItMatters: 'Control depends not on explicit violence but on a "magical a priori" — allusions to supernatural or unreal forces (white supremacy, divine right, brand soul) employed for mystification. Control is ultimately parasitic: it can only manage external resources, as none are genuinely its own. "Exteriority penetrates the interior all the way through — the withdrawal is always a facade."',
      tags: ['critique', 'institutions', 'power', 'emanationism'],
    },
    {
      id: 'cognitive_warfare',
      label: 'Cognitive Warfare',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'The enclosure of attention and sensory life — surveillance capitalism, algorithmic media, AI narrative compression, psychological targeting architectures, and aesthetic conditioning as governance. Platform monopolies are the contemporary enclosers of the cognitive commons, operating the same logic as the 17th-century enclosure of common lands.',
      whyItMatters: '"Thus came enclosure — ruin was her guide." The Emanationist cosmology that justified colonial projects is the same metaphysical infrastructure that justifies cognitive enclosure today. Open protocolization is the counter-strategy: keeping productive processes illegible to enclosing powers.',
      tags: ['surveillance', 'media', 'enclosure', 'Stiegler'],
      researchPaths: [
        { title: 'Algorithmic enclosure mechanics', body: 'Map the specific mechanisms (recommendation engines, engagement optimization, notification architecture) through which platform monopolies enclose the cognitive commons. What makes these structurally analogous to 17th-c land enclosure, and where does the analogy break down?' },
        { title: 'Aesthetic conditioning as governance', body: 'How do design languages (dark patterns, infinite scroll, persuasive UI) function as pastoral power? What is the relationship between aesthetic capture and political subjectivity?' },
        { title: 'AI narrative compression', body: 'How do LLM-mediated information environments compress and homogenize discourse? What does this mean for the cognitive commons?' },
        { title: 'Counter-strategies', body: 'Assess d/acc proposals as responses to cognitive warfare. What specific technical designs exist and how adequate are they?' },
      ],
    },
    {
      id: 'institutional_mind',
      label: 'The Institutional Mind',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'Control organizations function through an administrative elite analogous to a priest class — shuffling papers and metaphysical presumptions, mystifying the relational power that actually animates their protocols. Institutional mind-blindness, bureaucratic epistemology, legibility regimes, and process fascism are its contemporary faces.',
      whyItMatters: 'Process fascism is the cutting edge: institutions adopting rhizomatic, open, participatory forms as a new capture strategy. Members of control organizations are "less complicit than complacent — seduced by the comfort of hierarchical necessity, the perceived safety of withdrawal from the broader field of relations."',
      tags: ['institutions', 'epistemology', 'capture', 'control'],
      researchPaths: [
        { title: 'Empirical typology of bureaucratic epistemology', body: 'What specific knowledge-production failures characterize administrative institutions? Develop from case studies (university, hospital, state agency, NGO).' },
        { title: 'The priest-class analogy', body: 'Who are the contemporary administrative elites? How specifically do they mystify relational power — what are the concrete mechanisms of mystification?' },
        { title: 'Legibility regimes today', body: "Apply James C. Scott's analysis of state simplification to contemporary tech governance, platform policy, and algorithmic legibility. Where are the productive illegibilities?" },
        { title: 'Process fascism in practice', body: 'Case studies of administrative process that becomes its own end, foreclosing substantive judgment. What organizational conditions produce this?' },
        { title: 'Extitutional circumvention', body: 'Which extitutional responses have successfully routed around institutional mind-blindness? What made them work?' },
      ],
    },
    {
      id: 'ontologies_control',
      label: 'Ontologies of Control',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'Emanationism: the cosmological logic according to which all power flows downward from a unitary First Principle — God, Sovereign, Brand, Blood, Nation. Entities are ranked by proximity to this source. This is the deep structural logic underlying contemporary control organizations: nation-states, commercial brands, cults of charismatic leadership.',
      whyItMatters: 'Against Emanationism: the "network heresy" — powers of creation are democratized and relationalized, arising from the interaction of parts. From Linnaeus to Donati: "net rather than a chain." DAOs are the latest battleground: "The DAO form represents, sooner or later, the death of the ban." Bitcoin\'s genesis block asked: could we construct belief network effects without hierarchies?',
      tags: ['ontology', 'emanationism', 'philosophy', 'network-heresy'],
      researchPaths: [
        { title: 'Emanationism genealogy', body: 'Trace the theological origins of emanationist logic through sovereign power, brand culture, and techno-solutionism. Key texts: Plotinus, Bodin, Hobbes — and their contemporary successors.' },
        { title: 'The network heresy tradition', body: 'Who are the thinkers of the network heresy? Map the lineage: Spinoza, Tarde, Whitehead, Latour, Haraway, DeLanda. What is the core philosophical claim each is making?' },
        { title: 'Flat ontology and protocol design', body: "What are the specific implications of Latour's actor-network theory and DeLanda's neo-materialism for protocol design? What would a flat-ontological protocol look like?" },
        { title: 'Emanationism in contemporary ideology', body: 'How does emanationist logic structure nationalism, AI accelerationism, and platform capitalism? What are the specific rhetorical and organizational moves?' },
        { title: 'Afropessimism and ontological violence', body: 'Engage Patterson, Hartman, Moten, Sexton: what is the relationship between their account of anti-Black ontological violence and the general critique of control? Where does the specificity of their argument resist generalization?' },
      ],
    },
    {
      id: 'political_economy_control',
      label: 'Political Economy of Control',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'The Moloch meme describes coordination failures — multipolar traps where rational actors collectively produce outcomes none desire. But the frame overextends: it cannot address problems whose roots are axiomatic, pre-rational ontological assumptions that define the game board and the players themselves rather than the game.',
      whyItMatters: 'Drawing on Afropessimist tradition (Patterson, Hartman, Moten, Sexton): "The game of white supremacy can\'t be solved without appeal to the ontological ground on which it is played." The antidote to the deeper Moloch is not a credibly neutral arbiter but open-ended intelligence — design practices capable of self-reflexively interrogating their own ontological assumptions.',
      tags: ['political-economy', 'Moloch', 'afropessimism', 'OEI'],
      researchPaths: [
        { title: 'Moloch discourse critique', body: "Conduct a close reading of the Moloch meme's use in web3 and EA circles. Where exactly does the coordination-failure frame fail? What types of problem does it structurally cannot address?" },
        { title: 'Axiomatic violence and economics', body: 'What are the pre-rational ontological assumptions embedded in mainstream economic theory? How do these define the game board in ways rational-choice analysis cannot see?' },
        { title: 'Afropessimist political economy', body: 'What economic formations and dynamics do Moten, Sexton, Hartman identify that lie outside the Moloch frame? What would it mean to build an economic theory from their starting point?' },
        { title: 'Mutualism as alternative', body: 'Develop the relationship between Proudhonian mutualism, contemporary commons economics (Ostrom), and the extitutional form. What is the political economy of substrate?' },
        { title: 'OEI and value theory', body: "What does Weinbaum and Veitas' OEI framework imply for economic value? Can progressively coordinating heterogeneous agents generate a non-accumulative value theory?" },
      ],
    },
    {
      id: 'cognitive_infra_capture',
      label: 'Cognitive Infrastructure Capture',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'The enclosure of the internet by platform monopolies, of money by financialized institutions, of knowledge by NDAs and classification, and of aesthetic life by administrative space design. "Working class poet" John Clare documented the devastation of land enclosure in 1821; the same process now operates at the level of mind and attention.',
      whyItMatters: 'Ethereum is framed as a technology of de-enclosure: offering "permissive abundance of network wealth" against "premises of ownership of that which cannot be owned." BCI, VR, and AR are contested protocol terrain — either designed for cognitive enclosure or for cognitive sovereignty. The infrastructure choice is not neutral.',
      tags: ['platform', 'infrastructure', 'enclosure', 'de-enclosure'],
      researchPaths: [
        { title: 'Internet enclosure map', body: 'Detailed account of how platform monopolies captured the open internet: which platforms, what mechanisms (API closures, data moats, network effects as enclosure), what legal instruments (DMCA, ToS regimes)?' },
        { title: 'Ethereum as de-enclosure', body: "Critically examine Ethereum's claim to be a technology of de-enclosure. What specific mechanisms does it deploy? What are the limits and failure modes?" },
        { title: 'Financialization as monetary enclosure', body: 'What does it mean concretely for money to be enclosed by financialized institutions? Research the mechanisms: derivatives, repo markets, credit creation, shadow banking.' },
        { title: 'Aesthetic life enclosure', body: 'Map the enclosure of aesthetic life through administrative space design (airports, shopping malls, office parks, university campuses). What are the canonical examples and what design logics drive them?' },
        { title: 'IP law as enclosure instrument', body: 'How do copyright, patent, and trade secret law function as enclosure mechanisms for knowledge and aesthetic commons? What reform proposals exist?' },
      ],
    },

    // Movement II: Investigation of the Archive
    {
      id: 'archive',
      label: 'Investigation of the Archive',
      type: 'core',
      cluster: 'archive',
      radius: 22,
      summary: 'Excavating protocol undergrounds as empirical archives. Loose, informal communities tethered by open protocols — CA LSD underground, UK Free Party movement, Bay Area S&M scene, Hong Kong 2019 — solved under legal pressure the coordination problems institutions claim are unsolvable. Their protocols are recoverable and transmissible.',
      whyItMatters: 'Overgrounding is the method: taking underground values (high agency, consent culture, participatory aesthetics, ontological creativity) and creating scaffolding for horizontal circulation — distributing the protocols rather than the organization, letting practices spread while organizational containers remain minimal, ephemeral, and forkable.',
      tags: ['history', 'archive', 'overgrounding', 'protocol'],
    },
    {
      id: 'protocol_underground',
      label: 'The Protocol Underground',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Loose, informal communities tethered together only by open protocols, in which extitutional dynamics are dominant. Protocol undergrounds emerge wherever aesthetic practices face legal prohibition — because they cannot build storefronts or centralized academies, they protocolize, becoming more pluralistic and more resistant to institutional capture. High agency · Participatory aesthetics · Ontological creativity.',
      whyItMatters: 'Historical examples: California LSD scene (pricing ethics and spiritual anarchism resisted cartel capture); UK Free Party Movement (logistics of obscure illegal locations repelled passive consumerism); Bay Area S&M scene (elaborate consent protocols under legal persecution); Hong Kong 2019 (tactical protocols cross-contaminated across continents). Their illegibility to institutions is a feature, not a failure.',
      tags: ['protocol', 'history', 'underground', 'high-agency'],
      researchPaths: [
        { title: 'Case study depth', body: 'Conduct detailed comparative studies of the four named undergrounds (CA LSD scene, UK Free Party movement, Bay Area S&M scene, Hong Kong 2019). What specific protocols did each develop? What legal pressures drove protocolization?' },
        { title: 'Testing the three-characteristic model', body: 'Do all protocol undergrounds exhibit high agency, participatory aesthetics, and ontological creativity? Where does the model strain? Are there counterexamples?' },
        { title: 'Candidate undergrounds', body: 'What other communities qualify as protocol undergrounds? Apply the structural criteria to: harm reduction networks, pirate radio, cypherpunk mailing lists, ACT UP, Zapatista networks. What is the minimum criteria for membership?' },
        { title: 'Overgrounding pressure', body: 'What happened to the named undergrounds when they faced overgrounding? Which elements survived formalization, which were lost? What does this teach about the overgrounding process?' },
        { title: 'Protocolization dynamics', body: 'How does a community move from informal practice to open protocol? What triggers the shift? What is lost and gained?' },
      ],
    },
    {
      id: 'underground_epistemic',
      label: 'Underground Epistemic Cultures',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Underground cultures have been avant-gardes of consent culture — not as legal formality but as living, continuous, participatory practice. The S&M scene\'s "two squeezes" technique formalizes ongoing consent without breaking the mood. High agency as mutual assumption: distributed vigilance replacing institutional guarantees.',
      whyItMatters: 'In institutional settings, "interpretive labor" creates ambiguity about what is coercive and what voluntary. In extitutional settings, consent is not delegated to institutional guarantees but maintained through mutual expectation and continuous renegotiation. Underground communities also develop hermetic knowledge transmission and adversarial epistemics under legal pressure — generating epistemic forms unavailable to legitimate institutions.',
      tags: ['epistemology', 'consent', 'high-agency', 'underground'],
      researchPaths: [
        { title: 'Consent culture ethnography', body: 'Develop a detailed account of how consent culture actually functions in S&M scene practice. The "two squeezes" technique: what is its full social context? What makes it work, and what are its failure modes?' },
        { title: 'High agency as distributed vigilance', body: 'How does the mutual assumption of high agency function as a distributed safety system? What are the specific failure modes when individual actors defect? What social mechanisms repair the system?' },
        { title: 'Comparative consent cultures', body: 'How do different underground communities formalize ongoing agreement? Compare: kink scene, radical faerie gatherings, burner culture, harm reduction services, transformative justice networks.' },
        { title: 'Aesthetic participation and epistemic agency', body: 'What is the relationship between participatory aesthetics and the epistemic quality of underground communities? Does aesthetic participation produce different knowledge than spectatorship?' },
        { title: 'Material prerequisites for high agency', body: 'What social, economic, and physical conditions make high-agency culture possible? What is the relationship between precarity and agency in underground contexts?' },
      ],
    },
    {
      id: 'economies_virtual',
      label: 'Economies of the Virtual',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Undercapital: the expanse of economic value visible once virtual capital is recognized as a ninth form alongside Gregory Landua\'s eight forms. The virtual is "real but not actual" — the generative field of potentiality that animates material processes without being directly quantifiable. Protocol undergrounds have organized around nondual experiences of possibility as a core logistical resource.',
      whyItMatters: 'The virtual is not supernatural: protocol undergrounds demonstrate it is available for direct, demystified encounter. Concealment and capture of virtual energies is a vector of control; horizontal social engagement with the virtual is a passage of collective liberation. Building economic systems that prioritize virtual capital may require a design overhaul analogous to quantum physics\' overhaul of classical mechanics.',
      tags: ['economics', 'virtual', 'undercapital', 'Deleuze-Bergson'],
      researchPaths: [
        { title: 'Undercapital as ninth form', body: "Where precisely does Gregory Landua's eight-forms-of-capital framework leave a gap that undercapital fills? Develop the philosophical argument for virtual capital's status as a materially real productive force." },
        { title: 'The virtual in economics', body: "What would Bergson and Deleuze's concept of the virtual mean in economic terms? Which existing heterodox economic frameworks implicitly recognize something like virtual capital?" },
        { title: 'Empirical cases', body: "What existing economic practices recognize and mobilize virtual capital without naming it? Research: gift economies, commons governance, rave culture's gift/barter hybrids, mutual aid networks." },
        { title: 'Nondual experiences as logistical resource', body: 'What empirical evidence exists for the claim that nondual or altered states function as logistical resources in underground communities? Psychedelic research, contemplative tradition, somatic practice.' },
        { title: 'Accounting for the virtual', body: 'What would practical accounting for undercapital look like? Develop from existing experiments in alternative economic measurement (SROI, wellbeing economics, doughnut economics).' },
      ],
    },
    {
      id: 'immanent_tradition',
      label: 'The Immanent Tradition',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Lewis Mumford\'s neotechnic epoch — electricity and alloy complex carrying the potential for decentralized production — as historical analogue for the current protocol moment. Process philosophy (Whitehead, Bergson, Deleuze) · Feminist new materialisms (Barad, Haraway, Braidotti) · Neurophenomenology and enactivism (Varela, Maturana) · The Undercommons (Moten, Harney).',
      whyItMatters: '"We are the neotechnics": decentralized ledger technology is continuous with a longer history of distributed production infrastructure. The neotechnic toolkit is largely mature but politically underutilized — the exit from extractivist, centralized regimes has not caught up with the liberatory capacities of the neotechnic energy paradigm. Ethereum and web3 are the missing coordination layer.',
      tags: ['philosophy', 'immanence', 'neotechnics', 'Mumford'],
      researchPaths: [
        { title: 'Mumford and DLT', body: "Develop the analogy between Lewis Mumford's neotechnic epoch and current distributed ledger technology. Where is the analogy structurally sound? Where does it require qualification or break down?" },
        { title: 'Process philosophy and protocols', body: "What specifically does Whitehead's process philosophy, Bergson's durée, and Deleuze's difference and repetition offer to protocol design? Develop concrete design implications." },
        { title: 'Feminist new materialisms', body: "How do Barad's agential realism, Haraway's situated knowledge, and Braidotti's posthumanism bear on protocol ontology? What do they require of a 'feminist protocol'?" },
        { title: 'Neurophenomenology and distributed cognition', body: "What do Varela and Maturana's autopoiesis and enaction theory imply for the design of distributed cognitive systems? How does this connect to protocol underground dynamics?" },
        { title: 'The Undercommons', body: "What is Moten and Harney's specific contribution? How does the undercommons as a concept relate to substrate and extitutional space? Where does their analysis resist or enrich the protocol underground framework?" },
      ],
    },
    {
      id: 'ecological_intelligence',
      label: 'Ecological Intelligence Traditions',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Cooperation, not competition, is the primary driver of evolutionary complexity. Indigenous ecological knowledge systems · Systems ecology · Biosemiotics (von Uexküll: Umwelt) · Morphogenetic biology (Levin: diverse intelligence, basal cognition) · Autopoiesis (Varela, Maturana) · Symbiogenesis (Margulis).',
      whyItMatters: 'These traditions provide the empirical and conceptual basis for designing with ecological intelligence rather than against it. Levin\'s diverse intelligence expands the roster of cognitive agents we can coordinate with. Margulis: the great evolutionary leaps are cooperative mergers, not competitive victories — a design principle for extitutional infrastructure.',
      tags: ['ecology', 'intelligence', 'biology', 'indigenous'],
      researchPaths: [
        { title: 'Basal cognition synthesis', body: "Synthesize Levin's bioelectric cognition, Shapiro's natural genetic engineering, and Margulis' symbiogenesis into a coherent research program. What are the empirically testable claims? What are the implications for distributed intelligence design?" },
        { title: 'Umwelt and multi-agent design', body: "Apply von Uexküll's Umwelt theory to the design of multi-agent economic and governance systems. What does it mean to design a system that can engage diverse perceptual worlds? What is the 'umwelt gap' in practice?" },
        { title: 'Symbiogenesis as protocol model', body: "How does Margulis' symbiogenesis model inform thinking about protocol evolution? What would a symbiogenetic protocol look like?" },
        { title: 'Indigenous ecological knowledge', body: 'What specific traditions encode distributed intelligence and commons governance? Research: reciprocal maintenance relationships, seasonal rounds, potlatch economies, polycentric irrigation systems.' },
        { title: 'Cooperation as primary driver', body: 'Develop the empirical case that cooperation, not competition, is the primary driver of evolutionary complexity. What are the strongest counterarguments? What does this mean for economic design?' },
      ],
    },
    {
      id: 'underground_governance',
      label: 'Underground Governance Experiments',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Ethereum Localism: a strategy of reciprocal mimesis between open internet protocols and the open pragmatist cultures of cities and bioregions. Both are defined not by what they are but by what they can do — both share immediacy, pirate empiricism, and dread of coercive authority. Temporary autonomous zones · Commons governance (Ostrom) · Council-DAOs · Cosmo-local governance.',
      whyItMatters: 'Cities are anticapture devices: too complex to control, too many corridors of guerrilla resistance and flight. The greatest gifts Ethereum can offer protocol undergrounds: low overhead organizations, scale-agnostic models, "revenue evil" hacks. Adequate technology versus extractive technology — not "low tech" vs "high tech" but design orientation toward liberation versus extraction.',
      tags: ['governance', 'DAOs', 'ethereum-localism', 'cosmo-local'],
      researchPaths: [
        { title: 'Ethereum Localism case studies', body: 'What implementations of Ethereum Localism exist? Research: Gitcoin, Protocol Berg, Regen Network, local DAO experiments. What works and what fails, and why?' },
        { title: 'TAZ revisited', body: "Critically assess Hakim Bey's Temporary Autonomous Zone as a precursor to extitutional theory. What does the TAZ framework get right? Where does it fail (romanticism, temporariness, lack of protocol)?" },
        { title: "Ostrom's principles applied", body: "How do Ostrom's eight design principles for commons governance apply to protocol undergrounds and DAO structures? What do digital commons require that physical commons don't?" },
        { title: 'Council-DAO implementations', body: 'What council-DAO designs have been built and tested? What are their governance outcomes? What failure modes have emerged?' },
        { title: 'Cities as anticapture devices', body: 'What specific mechanisms make cities resistant to ideological and corporate capture? Research urban commons, sanctuary city politics, municipalist movements (Barcelona, Bologna). What structural features matter?' },
      ],
    },

    // Movement III: The Construction of Immanent Technology
    {
      id: 'construction',
      label: 'The Construction of Immanent Technology',
      type: 'core',
      cluster: 'construction',
      radius: 22,
      summary: 'Overgrounding the underground at scale: making underground practices repeatable, memeable, and formally legible — without standardizing or institutionalizing them. Distributed Ledger Technologies may offer a chance to do the impossible: scale the underground, embolden communities everywhere with participatory agency over the aesthetic environments they inhabit.',
      whyItMatters: 'Many scene veterans accept that "to scale is to die" — vertical scaling opens the door to institutionalization, passive consumption, cults of personality, hierarchical capture. Overgrounding proposes a horizontal alternative: distributing the protocols rather than the organization, letting practices spread through open circulation while containers remain minimal, ephemeral, and forkable.',
      tags: ['construction', 'overgrounding', 'design', 'immanence'],
    },
    {
      id: 'immanent_criteria',
      label: 'Immanent Technology Criteria',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Formalization without standardization: achieving shared protocols for mutual coherence without imposing hegemonic claims or institutional authority. Memeticism: actively encouraging divergent reproduction and mutation — a total lack of fealty to progenitors. Distribute agency · Enable aesthetic co-creation · Affirm consent · Provoke processual thinking · Design for open empiricism.',
      whyItMatters: 'Open protocols operate with "a total lack of fealty to their progenitors, forever remaining memetically open before the surround." Like McKenna\'s "self-transforming machine elves," they forge splintering paths through social adventures. Memetic success may itself be sufficient rubric for protocol value — especially under Retroactive Funding paradigms.',
      tags: ['criteria', 'memeticism', 'formalization', 'design'],
      researchPaths: [
        { title: 'Operationalizing formalization without standardization', body: 'Develop measurable criteria: when has a protocol crossed from formalization into standardization? What are the early warning signs? What design decisions tend to push toward each?' },
        { title: 'Memeticism as design principle', body: 'What specific design features make a protocol memetically active — spreading and mutating freely? Research: FOSS license structures, Creative Commons, open standards processes. What design decisions kill memeticism?' },
        { title: 'Open empiricism in practice', body: 'What does it concretely mean to design a protocol that is continuously revised by practical outcomes? What governance mechanisms enable this? What existing systems exhibit it?' },
        { title: 'Assessment framework', body: 'Develop a systematic rubric for evaluating existing protocols (DAOs, open standards, community currencies, governance frameworks) against the immanent technology criteria. Apply it to at least three cases.' },
        { title: 'Historical successes', body: 'What are the best historical examples of formalization without standardization? Candidates: Alcoholics Anonymous, UNIX philosophy, Quaker meeting procedure, Delphi technique, the GPL. What structural features account for their success?' },
      ],
    },
    {
      id: 'cognitive_sovereignty',
      label: 'Cognitive Sovereignty',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'High agency at scale: the mutual assumption that participants actively shape situations, infrastructures, and outcomes — not delegating basic material safety and vigilance to third parties. Self-owned cognitive infrastructure · Personal data autonomy · Local AI systems · Anti-manipulation architectures. Ethereum\'s non-coercive infrastructure proposed as a scaling mechanism for high-agency culture.',
      whyItMatters: 'One of the key hazards of scaling underground practices is the erosion of high-agency culture: institutional behavioral biases, passive consumption dynamics, and cults of personality withdraw agency from participants and concentrate it in administrators, figureheads, or platforms. Forkable, permissionless infrastructure is structurally hostile to the monopolization of agency.',
      tags: ['sovereignty', 'high-agency', 'autonomy', 'infrastructure'],
      researchPaths: [
        { title: 'Self-sovereign identity audit', body: 'Map existing SSI architectures (W3C DID, Verifiable Credentials, BrightID, Proof of Humanity) and assess them against cognitive sovereignty criteria. What do they achieve and what do they miss?' },
        { title: 'Local AI architectures', body: 'What does AI infrastructure look like when it is non-coercive, locally run, and substrate-embedded? Research: open-weight models, edge inference, federated learning, personal AI agents. What are the technical and social requirements?' },
        { title: 'Anti-manipulation design', body: 'What technical architectures resist psychological targeting and attention manipulation? Research: chronological feeds, user-controlled algorithms, attention budgets, non-addictive design patterns.' },
        { title: 'High-agency culture at scale', body: 'What social and institutional conditions, beyond technical infrastructure, are required for high-agency culture to function at scale? Research: Burning Man regional structure, harm reduction networks, libertarian municipal experiments.' },
        { title: 'Ethereum and cognitive sovereignty', body: "Where does Ethereum's current infrastructure succeed in enabling cognitive sovereignty, and where does it fail (gas costs, UX complexity, MEV, governance capture)?" },
      ],
    },
    {
      id: 'open_protocol_design',
      label: 'Open Protocol Design',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Memetic, empirical, anti-capture protocol design: protocols that circulate freely through the social field, crystallizing into maximally versatile and practical forms in diverse environments. The S&M scene\'s handbooks formalize safety protocols without standardizing what S&M should look or mean. FOSS formalizes sharing norms without standardizing what software should do.',
      whyItMatters: 'Anti-memeticism — military classification, NDAs, industrial secrets, proprietary knowledge — compresses behavior into optimal forms from a top-down source, "but they miss out on the modularity, fracture, and mischievous creativity of the publics." Forkability is the health indicator and anti-capture mechanism. The capacity to fork is what separates open protocols from enclosed standards.',
      tags: ['protocol', 'design', 'memeticism', 'forkability'],
      researchPaths: [
        { title: 'S&M handbook analysis', body: 'Conduct a structural analysis of how S&M scene safety handbooks (Townsend, Wiseman, StolenMoment) formalize safety without standardizing aesthetics. What are the formal design features that achieve this separation?' },
        { title: 'FOSS as governance model', body: 'What specific aspects of free and open source software development processes are applicable to non-software protocol governance? What does and does not translate?' },
        { title: 'Forkability metrics', body: 'Develop operational metrics for forkability as a protocol health indicator. What data would you need? How would you measure the practical cost of forking? What threshold marks an anticapture protocol?' },
        { title: 'Anti-capture mechanisms in practice', body: 'Which anti-capture mechanisms have proven most effective across different protocol contexts? Comparative analysis: ragequit (MolochDAO), forking (Linux/BSD split), constitutional constraints, sunset clauses, kill switches.' },
        { title: 'Memetic protocol design language', body: 'Develop a practical design vocabulary for creating memetically active protocols. What are the key variables? What are the tradeoffs between memetic vitality and protocol coherence?' },
      ],
    },
    {
      id: 'cognitive_ecology',
      label: 'Cognitive Ecology',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Noöpunk: the universe as a landscape of nested and entangled cognitive assemblages — minds distributed across organisms, ecosystems, dynamic material processes, and socio-technical networks. Cognition is not the exclusive property of human brains but distributed across a "carnival of diverse intelligence." Open-ended intelligence (Weinbaum/Veitas): distributed heterogeneous agents achieving progressively higher coordination through reciprocal determination.',
      whyItMatters: 'Noöpunk is also a political and economic program: nonhuman minds will remain marginalized until they can participate economically. This requires intersubjective and contextual monies adequate to a cognitive ecology. Open-ended intelligence dismisses the "a priori givens" of intelligence — agent, environment, the distinction between them — proposing identity as metastable and provisional: "stations in an incessant process of transformation."',
      tags: ['cognition', 'ecology', 'noöpunk', 'OEI'],
      researchPaths: [
        { title: 'Noöpunk research program', body: 'What specific empirical claims does the Noöpunk framework make that are testable? Develop a research agenda: what studies would confirm or disconfirm the view that the universe is a landscape of nested cognitive assemblages?' },
        { title: 'OEI technical implications', body: "What does Weinbaum and Veitas' Open-Ended Intelligence framework imply for multi-agent system design? What existing AI architectures exhibit OEI-like dynamics? What would a deliberately OEI-designed system look like?" },
        { title: 'Economic inclusion of nonhuman minds', body: 'What specific exclusions do current economic and governance systems impose on nonhuman cognitive agents (animal collectives, fungal networks, AI agents, ecosystems)? What design interventions could begin to address these?' },
        { title: 'Distributed cognition in socio-technical systems', body: "Study existing distributed cognitive systems (air traffic control, Wikipedia, open source projects, coral reef management) through Hutchins' framework. What design features produce robust distributed cognition?" },
        { title: 'Autopoiesis and protocol design', body: 'Can you design conditions for autopoietic emergence in protocol communities? What would this require? Research: communities that have developed self-sustaining cultural practices from minimal initial conditions.' },
      ],
    },
    {
      id: 'extitutional_infra',
      label: 'Extitutional Infrastructure',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Extitutions: small, often ephemeral organizational entities that use the benefits of institutional legibility to secure, protect, and formalize the open empiricism of protocol undergrounds. Institutional avatars of protocol undergrounds — deliberately deploying formal structure to shield informal networks from capture. Substrate: the permissionless social field that animates and checks organizational life.',
      whyItMatters: 'Historical examples: Brotherhood of Eternal Love (formalizing cheap LSD distribution); Spiral Tribe (institutionalizing free party ethos under legal pressure); Society of Janus (formalizing S&M consent culture); indie record labels of the 1990s designed to be run into the ground and resurrected. The walkaway test: can an organization be deliberately abandoned without loss to the protocol? DAOs — through ragequit, forks, and audits — represent "the death of the ban."',
      tags: ['extitution', 'substrate', 'protocol', 'walkaway-test'],
      researchPaths: [
        { title: 'Walkaway test as design criterion', body: 'Develop the walkaway test into a practical design tool. What does a protocol or organization need to build into itself to pass the test? What existing organizations could pass it today?' },
        { title: 'Historical extitution case studies', body: 'Detailed structural analysis of the three named historical extitutions: Brotherhood of Eternal Love, Spiral Tribe, Society of Janus. What organizational features made each effective? What caused their dissolution or transformation?' },
        { title: 'DAO anti-capture features', body: 'Systematic analysis of which DAO design features (ragequit, transparent governance, audits, fork rights) most effectively prevent institutional capture. Study cases where these features were tested under pressure.' },
        { title: 'Substrate formation and maintenance', body: 'What social practices build and sustain substrate? What causes substrate to dissolve? Research communities that have maintained strong substrate over time (Quakers, Burning Man, open source communities, mutual aid networks).' },
        { title: 'Extitutional failure modes', body: 'Develop a typology of how extitutions become institutions. Research historical cases: how did the Free Software Foundation, Wikimedia, Electronic Frontier Foundation drift from extitutional to institutional forms?' },
      ],
    },
    {
      id: 'process_economic_design',
      label: 'Process-Based Economic Design',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Undercapital as design practice: building economic systems that treat the virtual — the real but non-actualized field of potential — as a primary productive force. Intersubjective contextual monies encoding context and relation rather than abstracting from them. Intent-centric architectures (vagabond technology) organized around declared intent rather than identity or permission.',
      whyItMatters: 'Building economic systems that prioritize virtual capital may require a design overhaul analogous to quantum physics\' overhaul of classical mechanics — a shift from extensive, object-based accounting to intensive, processual, field-based models. Candidate technologies: intent-centric web3 applications, feral computing, and field ontology methods. "The felt sense of possibility is not epiphenomenal but causal — presence, trust, and affective charge are primary economic facts."',
      tags: ['economics', 'virtual', 'undercapital', 'intent-centric'],
      researchPaths: [
        { title: 'Intersubjective contextual monies', body: 'What would monies that encode context and relation rather than abstracting from them look like technically? Research: mutual credit (Greco), community currencies (Sardex, Bristol Pound), time banking, Sarafu network.' },
        { title: 'Vagabond technology', body: 'Develop the concept of intent-centric architecture. What existing systems organize around declared intent rather than identity or permission? Research: commitment devices, escrow, streaming payments, quadratic funding.' },
        { title: 'Felt sense as productive force', body: 'What would it mean to treat the felt sense of possibility as causally efficacious in economic design? Research somatic practice in organizational contexts, embodied decision-making, and the economics of morale and atmosphere.' },
        { title: 'Virtual capital in practice', body: "What existing community economic practices most closely approximate undercapital design? Develop case studies: gift economies, potlatch, burner culture economies, psychedelic retreat economics. What makes virtual capital mobile?" },
        { title: 'Virtual capital accounting', body: 'What accounting frameworks could track virtual capital flows alongside material ones? Research: Genuine Progress Indicator, SROI, natural capital accounting, relational wellbeing measurement. What is missing from each?' },
      ],
    },
    {
      id: 'posthuman_technogenesis',
      label: 'Posthuman Technogenesis',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Posthumanism critiques the humanist insistence on human cognitive supremacy, in light of cybernetic and systems-theoretic discoveries. Ethereum as posthuman infrastructure: permissionless, ontologically agnostic, capable of hosting zoological, ecological, and exotic cognitive agents. Egregores — collective psychic entities generated by focused attention — as candidates for empirical investigation and economic formalization.',
      whyItMatters: '"In the posthuman view, conscious agency has never been \'in control.\' In fact, the very illusion of control bespeaks a fundamental ignorance about the nature of the emergent processes through which consciousness, the organism, and the environment are constituted." The influx of "alien adversaries" that destabilized legacy institutions are the exact agencies that animate and strengthen the Ethereum thesis.',
      tags: ['posthumanism', 'egregore', 'ethereum', 'agency'],
      researchPaths: [
        { title: 'Zoological and ecological agents on Ethereum', body: 'What legal and technical infrastructure would be required for non-human agents (animal collectives, ecosystems, fungal networks) to hold Ethereum-based economic rights? Research existing experiments: Nonhuman Rights Project, rights of nature legislation, Whanganui River personhood.' },
        { title: 'Egregore empirics', body: 'What empirical methods could study collective psychic entities? Develop from: crowd psychology (Le Bon, Tarde), phenomenology of collective intentionality (Searle, Tuomela), participatory research in festival and underground contexts.' },
        { title: 'Flat-ontological governance', body: 'What would a governance system look like that genuinely included nonhuman agents as participants? What are the existing proposals and experiments? What are the insurmountable philosophical problems?' },
        { title: 'Posthumanist technology philosophy', body: 'Synthesize Hayles, Haraway, Stiegler, Braidotti on technology. What is the collective implication for protocol design? What would a posthumanist protocol explicitly reject about humanist protocol assumptions?' },
        { title: 'Cryptoeconomic nonhuman agency', body: 'What specific cryptoeconomic mechanisms could enable nonhuman agents to participate economically? Research: autonomous agents (smart contracts as proto-agents), prediction markets for non-human welfare, ecosystem service tokens, interspecies DAOs.' },
      ],
    },
  ],

  edges: [
    // Open Machine → movement cores
    { source: 'open_machine', target: 'critique',     type: 'direct_influence',  weight: 2 },
    { source: 'open_machine', target: 'archive',      type: 'direct_influence',  weight: 2 },
    { source: 'open_machine', target: 'construction', type: 'direct_influence',  weight: 2 },

    // Movement I → sections
    { source: 'critique', target: 'cognitive_warfare',         type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'institutional_mind',        type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'ontologies_control',        type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'political_economy_control', type: 'direct_influence', weight: 1 },
    { source: 'critique', target: 'cognitive_infra_capture',   type: 'direct_influence', weight: 1 },

    // Movement II → sections
    { source: 'archive', target: 'protocol_underground',  type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'underground_epistemic', type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'economies_virtual',     type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'immanent_tradition',    type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'ecological_intelligence', type: 'direct_influence', weight: 1 },
    { source: 'archive', target: 'underground_governance', type: 'direct_influence', weight: 1 },

    // Movement III → sections
    { source: 'construction', target: 'immanent_criteria',       type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'cognitive_sovereignty',   type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'open_protocol_design',    type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'cognitive_ecology',       type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'extitutional_infra',      type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'process_economic_design', type: 'direct_influence', weight: 1 },
    { source: 'construction', target: 'posthuman_technogenesis', type: 'direct_influence', weight: 1 },

    // Cross-movement spine
    { source: 'critique',  target: 'archive',      type: 'conceptual_affinity', weight: 2 },
    { source: 'archive',   target: 'construction', type: 'applied_extension',   weight: 2 },

    // Cross-concept connections (critique → construction)
    { source: 'cognitive_warfare',        target: 'cognitive_sovereignty',   type: 'applied_extension',   weight: 2 },
    { source: 'cognitive_infra_capture',  target: 'open_protocol_design',    type: 'applied_extension',   weight: 2 },
    { source: 'institutional_mind',       target: 'extitutional_infra',      type: 'applied_extension',   weight: 2 },
    { source: 'ontologies_control',       target: 'cognitive_ecology',       type: 'applied_extension',   weight: 2 },
    { source: 'political_economy_control', target: 'process_economic_design', type: 'applied_extension',  weight: 2 },

    // Cross-concept connections (archive → construction)
    { source: 'protocol_underground',    target: 'open_protocol_design',    type: 'applied_extension',   weight: 2 },
    { source: 'protocol_underground',    target: 'extitutional_infra',      type: 'conceptual_affinity', weight: 1 },
    { source: 'economies_virtual',       target: 'process_economic_design', type: 'applied_extension',   weight: 2 },
    { source: 'immanent_tradition',      target: 'cognitive_ecology',       type: 'conceptual_affinity', weight: 2 },
    { source: 'ecological_intelligence', target: 'cognitive_ecology',       type: 'applied_extension',   weight: 2 },
    { source: 'underground_governance',  target: 'extitutional_infra',      type: 'applied_extension',   weight: 2 },
    { source: 'underground_epistemic',   target: 'cognitive_sovereignty',   type: 'conceptual_affinity', weight: 1 },
    { source: 'immanent_tradition',      target: 'posthuman_technogenesis', type: 'conceptual_affinity', weight: 1 },
    { source: 'economies_virtual',       target: 'extitutional_infra',      type: 'conceptual_affinity', weight: 1 },
  ],
}

// ─── VISION 3 ────────────────────────────────────────────────────────────────

export const VISION_3 = {
  nodes: [
    {
      id: 'open_machine',
      label: 'Open Machine',
      type: 'open_machine',
      cluster: 'core',
      radius: 28,
      layer: 3,
      summary: 'A research and practice collective synthesizing immanent philosophy with emerging technology.',
      whyItMatters: 'The Open Machine inhabits all three movements simultaneously: diagnosing transcendent control structures, recovering protocol underground archives, and building immanent technological infrastructure.',
      tags: ['research', 'collective', 'immanence', 'protocol'],
    },

    // Layer 5 — Aesthetics & Phenomenology
    {
      id: 'layer5',
      label: 'Aesthetics & Phenomenology',
      type: 'core',
      cluster: 'aesthetics',
      radius: 22,
      layer: 5,
      summary: 'The fabric of collective sensory-cognitive life; how reality is felt and made as much as known.',
      whyItMatters: 'Aesthetics in the Stieglerian sense (aisthēsis) is the most fundamental layer — it shapes what can be perceived and experienced before any epistemology or coordination is possible.',
      tags: ['aesthetics', 'phenomenology', 'experience'],
    },
    {
      id: 'nopunk_l5',
      label: 'Noöpunk',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'The aesthetic-political movement seeing the universe as nested cognitive assemblages activating through art, music, computation, and ecology.',
      whyItMatters: 'Noöpunk is the felt practice of the entire stack — what living inside an immanent world looks and feels like.',
      tags: ['art', 'culture', 'cognition'],
    },
    {
      id: 'symbolic_commons',
      label: 'Symbolic Commons',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'Shared aesthetic and symbolic resources held in common — music, imagery, language, narrative — that enable collective sense-making outside market mediation.',
      whyItMatters: 'The symbolic commons is what cognitive enclosure destroys and what protocol undergrounds rebuild. It is the aesthetic infrastructure of community.',
      tags: ['commons', 'aesthetics', 'culture'],
    },
    {
      id: 'aisthesis',
      label: 'Aisthēsis',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'The pre-cognitive, bodily dimension of perception and sensory experience — what Stiegler identifies as the primary site of political-aesthetic contestation.',
      whyItMatters: 'Aisthēsis is why advertising and algorithmic media are more than annoyances — they restructure the perceptual substrate of collective life before thought begins.',
      tags: ['Stiegler', 'perception', 'politics'],
    },
    {
      id: 'technedelics_l5',
      label: 'Technedelics',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'Technologies and practices (psychedelics, VR, deep media) that enable encounter with radically foreign umwelts — alien sensory-cognitive worlds.',
      whyItMatters: 'Technedelics sit at the intersection of aesthetics and epistemology: they are the most radical form of perceptual expansion, testing the limits of what can be experienced and known.',
      tags: ['psychedelics', 'umwelt', 'experience'],
    },

    // Layer 4 — Coordination & Governance
    {
      id: 'layer4',
      label: 'Coordination & Governance',
      type: 'core',
      cluster: 'coordination',
      radius: 22,
      layer: 4,
      summary: 'How distributed agents act together without surrendering agency to a center — stigmergy, polycentric governance, consent culture, cosmo-local networks.',
      whyItMatters: 'Coordination is where ontology meets practice. The question is not whether to coordinate but on what terms — and with what relationship to diverse intelligences and open protocols.',
      tags: ['coordination', 'governance', 'collective'],
    },
    {
      id: 'cosmo_local_l4',
      label: 'Cosmo-Localism',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Heavy things local, light things global. Resilient bioregional production networked to shared knowledge commons.',
      whyItMatters: 'Cosmo-localism is the operational synthesis of the entire project — how to be rooted and connected without being isolated or homogenized.',
      tags: ['cosmo-localism', 'local', 'global'],
    },
    {
      id: 'stigmergy',
      label: 'Stigmergy',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Swarm coordination without central planning — agents signal through environmental modification, enabling positive-sum feedback loops (ants, Wikipedia, Burning Man).',
      whyItMatters: 'Stigmergy proves that complex collective coordination doesn\'t require hierarchy or central authority. It is the coordination mechanism of the protocol underground.',
      tags: ['swarm', 'emergence', 'coordination'],
    },
    {
      id: 'polycentric',
      label: 'Polycentric Governance',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Multiple overlapping scales of governance, each handling what is appropriate to its level — Ostrom\'s principle of subsidiarity applied to information and resource commons.',
      whyItMatters: 'Polycentric governance is how cosmo-localism gets operationalized institutionally: neither global monoculture nor local fragmentation but nested, overlapping jurisdictions.',
      tags: ['Ostrom', 'commons', 'governance'],
    },
    {
      id: 'consent_culture',
      label: 'Consent Culture',
      type: 'tradition',
      cluster: 'coordination',
      radius: 17,
      layer: 4,
      summary: 'The S/M community\'s development of explicit, ongoing, renegotiable consent as a full coordination protocol — now recoverable for broader social design.',
      whyItMatters: 'Consent culture is the protocol underground\'s answer to how you coordinate intimately without coercion. It is a working proof of concept for affirmative consent as governance principle.',
      tags: ['consent', 'protocol', 'ethics', 'history'],
    },
    {
      id: 'semiotic_bridging',
      label: 'Semiotic Bridging',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Revealing underlying compatibility between diverse movements and frameworks by translating between their distinct vocabularies without demanding ideological unity.',
      whyItMatters: 'Semiotic bridging is how cosmo-local coalitions are built. It is the communicative practice that allows diverse communities to coordinate without standardizing.',
      tags: ['communication', 'translation', 'coalition'],
    },

    // Layer 3 — Infrastructure
    {
      id: 'layer3',
      label: 'Infrastructure',
      type: 'core',
      cluster: 'infrastructure',
      radius: 22,
      layer: 3,
      summary: 'The formal substrate that makes coordination legible without making it capturable — open protocols, cryptographic consensus, distributed compute.',
      whyItMatters: 'Infrastructure is the layer that either enables or forecloses all layers above it. Open infrastructure is the technical precondition for immanent governance and aesthetics.',
      tags: ['infrastructure', 'protocol', 'technical'],
    },
    {
      id: 'ethereum',
      label: 'Ethereum',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Ontologically agnostic distributed compute infrastructure — capable of treating diverse forms of intelligence and agency symmetrically, without reference to human sovereignty.',
      whyItMatters: 'Ethereum is posthuman infrastructure: it provides formalization without standardization, minimum viable consensus through mathematics rather than institutional authority.',
      tags: ['Ethereum', 'blockchain', 'posthumanism'],
    },
    {
      id: 'open_protocols',
      label: 'Open Protocols',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Memetic, empirical, anti-capture protocol design — reproducible, forkable, adaptable to local context without losing coherence.',
      whyItMatters: 'Open protocols are the formalization without standardization that allows underground practices to scale. They are the technical instantiation of the isomorphism thesis.',
      tags: ['protocol', 'open-source', 'design'],
    },
    {
      id: 'daos',
      label: 'DAOs',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Decentralized autonomous organizations: smart-contract-based coordination mechanisms that formalize governance without requiring institutional authority.',
      whyItMatters: 'DAOs are the organizational form corresponding to extitutional strategy — they use institutional legibility (legal wrappers) while remaining operationally committed to distributed governance.',
      tags: ['DAOs', 'governance', 'smart-contracts'],
    },
    {
      id: 'mycofi',
      label: 'MycoFi',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Fungal network models applied to distributed resource allocation — the mycelium as both metaphor and template for peer-to-peer economic coordination.',
      whyItMatters: 'MycoFi extends cosmo-localism into regenerative economics, proposing that resource flows can be organized according to ecological rather than market logics.',
      tags: ['ecology', 'economics', 'distributed'],
    },

    // Layer 2 — Epistemology & Cognition
    {
      id: 'layer2',
      label: 'Epistemology & Cognition',
      type: 'core',
      cluster: 'epistemology',
      radius: 22,
      layer: 2,
      summary: 'What counts as knowing, who counts as a knower, and who controls the conditions of perception — the contested layer of diverse intelligence and cognitive sovereignty.',
      whyItMatters: 'Epistemology is where the philosophical and the political converge: controlling how we know is controlling how we can act and what we can coordinate with.',
      tags: ['epistemology', 'cognition', 'sovereignty'],
    },
    {
      id: 'diverse_intel_l2',
      label: 'Diverse Intelligence',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Michael Levin\'s framework: intelligence as distributed across nested problem-solving systems — cells in metabolic space, organisms in physical space, collectives in social space.',
      whyItMatters: 'Diverse intelligence expands the roster of cognitive agents we can coordinate with, and provides the epistemological ground for posthumanist infrastructure design.',
      tags: ['Levin', 'intelligence', 'cognition'],
    },
    {
      id: 'cog_sovereignty_l2',
      label: 'Cognitive Sovereignty',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Freedom from institutional determination of thought and perception — the positive capacity to appraise and engage diverse intelligences from a position of epistemic autonomy.',
      whyItMatters: 'Cognitive sovereignty is the personal and collective counterpart to open protocol infrastructure: it is what free infrastructure enables and what cognitive enclosure destroys.',
      tags: ['sovereignty', 'autonomy', 'cognition'],
    },
    {
      id: 'umwelt',
      label: 'Umwelt',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Jakob von Uexküll\'s concept: each organism inhabits a unique perceptual world defined by its sensory apparatus and cognitive capacities. Encountering alien umwelts expands epistemic space.',
      whyItMatters: 'Umwelt thinking is the perceptual foundation of diverse intelligence: to recognize other minds, you must be able to conceive that other perceptual worlds exist and are real.',
      tags: ['umwelt', 'perception', 'biology'],
    },
    {
      id: 'dist_cognition',
      label: 'Distributed Cognition',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Edward Hutchins\' framework: cognitive processes extend beyond individual minds into socio-technical systems. Ships navigate, teams problem-solve, cities remember.',
      whyItMatters: 'Distributed cognition grounds the stigmergy claim: collective intelligence is not metaphorical but literally cognitive — the system knows things no individual knows.',
      tags: ['Hutchins', 'cognition', 'systems'],
    },
    {
      id: 'technedelics_l2',
      label: 'Technedelics (Epistemic)',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Psychedelics and radical media as epistemological tools: empirical access to alien umwelts, direct test of the limits of cognitive sovereignty.',
      whyItMatters: 'From the epistemological layer, technedelics are less about experience and more about what they prove: that other cognitive worlds are real and accessible, and that the sovereign observer is a construction.',
      tags: ['psychedelics', 'epistemology', 'umwelt'],
    },

    // Layer 1 — Ontology
    {
      id: 'layer1',
      label: 'Ontology',
      type: 'core',
      cluster: 'ontology',
      radius: 22,
      layer: 1,
      summary: 'What is real; what kinds of agency exist; what is the nature of creative emergence — the philosophical ground of the entire stack.',
      whyItMatters: 'Ontology is not the most abstract layer but the most fundamental. Every design decision about infrastructure, governance, and aesthetics encodes ontological assumptions. Making them explicit is the work of layer 1.',
      tags: ['ontology', 'philosophy', 'metaphysics'],
    },
    {
      id: 'immanence',
      label: 'Immanence',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Deleuzian concept: creative capacity arising from relational fields without central command. Power distributed within, not emanating from above. Against transcendence in all its forms.',
      whyItMatters: 'Immanence is the unifying philosophical principle of the entire project. It names what the three movements and five layers are all, in their different registers, trying to instantiate.',
      tags: ['Deleuze', 'immanence', 'philosophy'],
    },
    {
      id: 'the_virtual',
      label: 'The Virtual',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Deleuze\'s reading of Bergson: the virtual is real but not actual — the generative field of potentiality that animates material processes without being directly quantifiable.',
      whyItMatters: 'The virtual is why undercapital is real economics, why the underground matters, why aesthetic experience is productive. It names the dimension that institutional accounting cannot see.',
      tags: ['Deleuze', 'Bergson', 'virtual', 'potentiality'],
    },
    {
      id: 'undercapital_l1',
      label: 'Undercapital',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'The ontological claim behind the economic concept: that the virtual dimension is a real productive force, and that organizing to access it generates genuine value.',
      whyItMatters: 'Undercapital at the coordination layer is the claim that the felt sense of possibility is not epiphenomenal but causal — that presence, trust, and affective charge are primary economic facts.',
      tags: ['economics', 'virtual', 'coordination'],
    },
    {
      id: 'open_ended',
      label: 'Open-Ended Intelligence',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Weinbaum & Veitas: intelligence as distributed, self-reflexive, and without terminal state — the rejection of goal-optimization for open-ended adaptive becoming.',
      whyItMatters: 'Open-ended intelligence is the ontological basis for diverse intelligence: if intelligence has no fixed goal, it cannot be defined by its output but only by its processual character.',
      tags: ['intelligence', 'AI', 'becoming'],
    },
    {
      id: 'posthumanism',
      label: 'Posthumanism',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Rejection of the autonomous sovereign subject as the primary unit of moral and political consideration — distributed agency at all scales, from cells to collectives.',
      whyItMatters: 'Posthumanism is the ontological foundation for Ethereum\'s technical design (no reference to human sovereignty), for diverse intelligence research, and for bioregional governance.',
      tags: ['posthumanism', 'agency', 'subject'],
    },
  ],

  edges: [
    { source: 'open_machine',      target: 'layer5',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer4',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer3',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer2',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer1',            type: 'direct_influence',   weight: 2 },
    { source: 'layer5',            target: 'nopunk_l5',         type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'symbolic_commons',  type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'aisthesis',         type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'technedelics_l5',   type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'cosmo_local_l4',    type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'stigmergy',         type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'polycentric',       type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'consent_culture',   type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'semiotic_bridging', type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'ethereum',          type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'open_protocols',    type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'daos',              type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'mycofi',            type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'diverse_intel_l2',  type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'cog_sovereignty_l2', type: 'direct_influence',  weight: 1 },
    { source: 'layer2',            target: 'umwelt',            type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'dist_cognition',    type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'technedelics_l2',   type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'immanence',         type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'the_virtual',       type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'undercapital_l1',   type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'open_ended',        type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'posthumanism',      type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'layer2',            type: 'applied_extension',  weight: 3 },
    { source: 'layer2',            target: 'layer3',            type: 'applied_extension',  weight: 3 },
    { source: 'layer3',            target: 'layer4',            type: 'applied_extension',  weight: 3 },
    { source: 'layer4',            target: 'layer5',            type: 'applied_extension',  weight: 3 },
    { source: 'immanence',         target: 'diverse_intel_l2',  type: 'conceptual_affinity', weight: 2 },
    { source: 'the_virtual',       target: 'undercapital_l1',   type: 'conceptual_affinity', weight: 2 },
    { source: 'open_ended',        target: 'diverse_intel_l2',  type: 'conceptual_affinity', weight: 2 },
    { source: 'posthumanism',      target: 'ethereum',          type: 'applied_extension',  weight: 2 },
    { source: 'umwelt',            target: 'technedelics_l5',   type: 'conceptual_affinity', weight: 2 },
    { source: 'stigmergy',         target: 'open_protocols',    type: 'conceptual_affinity', weight: 2 },
    { source: 'consent_culture',   target: 'daos',              type: 'applied_extension',  weight: 2 },
    { source: 'cosmo_local_l4',    target: 'mycofi',            type: 'conceptual_affinity', weight: 1 },
    { source: 'aisthesis',         target: 'symbolic_commons',  type: 'conceptual_affinity', weight: 1 },
    { source: 'dist_cognition',    target: 'stigmergy',         type: 'conceptual_affinity', weight: 2 },
    { source: 'technedelics_l2',   target: 'technedelics_l5',   type: 'conceptual_affinity', weight: 1 },
  ],
}
