export const COLORS = {
  critique:       '#c4622d',
  archive:        '#4a7c59',
  construction:   '#3d5a8a',
  aesthetics:     '#7c5cbf',
  coordination:   '#2a8a7a',
  infrastructure: '#c07a28',
  epistemology:   '#3a6ea8',
  ontology:       '#5a3a8a',
  core:           '#1a1510',
}

// ─── VISION 2 ────────────────────────────────────────────────────────────────

export const VISION_2 = {
  nodes: [
    {
      id: 'open_machine',
      label: 'Open Machine',
      type: 'open_machine',
      cluster: 'core',
      radius: 28,
      summary: 'A research and practice collective synthesizing immanent philosophy with emerging technology.',
      whyItMatters: 'The Open Machine inhabits all three movements simultaneously: diagnosing transcendent control structures, recovering protocol underground archives, and building immanent technological infrastructure.',
      tags: ['research', 'collective', 'immanence', 'protocol'],
    },

    // Movement I: Critique
    {
      id: 'critique',
      label: 'The Critique of Control',
      type: 'core',
      cluster: 'critique',
      radius: 22,
      summary: 'Analysis of how institutional logics, hierarchical ontologies, and control architectures systematically capture and diminish collective intelligence.',
      whyItMatters: 'Critique maps the mechanisms we must navigate: Molochian competition, cognitive enclosure, ontological hierarchy, mind-blindness. Understanding what we resist is as important as what we build.',
      tags: ['critique', 'institutions', 'power', 'diagnosis'],
    },
    {
      id: 'moloch',
      label: 'The Moloch Problem',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'How competitive dynamics produce collectively irrational outcomes — races to the bottom that no individual agent wants but all are compelled toward.',
      whyItMatters: 'Moloch names the structural dynamic driving surveillance capitalism, arms races, and extractive markets. Naming it allows us to design coordination mechanisms where cooperation is the dominant strategy.',
      tags: ['coordination', 'game-theory', 'incentives'],
    },
    {
      id: 'enclosure',
      label: 'Cognitive Enclosure',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'The systematic capture of collective sensory and intellectual capacity by commercial and state interests — advertising, algorithmic media, surveillance, ideological formation.',
      whyItMatters: 'Cognitive enclosure is the privatization not of land but of attention. It is the material foundation of manufactured consent and the primary target of the cognitive sovereignty project.',
      tags: ['attention', 'surveillance', 'media'],
    },
    {
      id: 'ontological_hierarchy',
      label: 'Ontological Hierarchy',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'The Great Chain of Being as operating system: hierarchical ontologies that legitimate control by establishing who counts as an agent, knower, or rights-holder.',
      whyItMatters: 'Ontological hierarchy is how power legitimates itself philosophically. Challenging it requires not just political but ontological work — redesigning the substrate of who and what counts.',
      tags: ['ontology', 'power', 'philosophy'],
    },
    {
      id: 'mind_blindness',
      label: 'Mind-Blindness',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'The institutional refusal to recognize intelligence and agency outside its own categories — the failure to see cognition in cells, collectives, ecosystems, or non-western practices.',
      whyItMatters: 'Mind-blindness is the cognitive tax of anthropocentrism. It forecloses vast design spaces and perpetuates extractive relationships with non-human systems that are in fact intelligent agents.',
      tags: ['cognition', 'anthropocentrism', 'intelligence'],
    },
    {
      id: 'critique_emanationism',
      label: 'The Critique of Emanationism',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'A critique of emanationist frameworks — systems in which power, meaning, or being radiates outward from a single transcendent source, structuring hierarchy from the top down.',
      whyItMatters: 'Emanationism is the metaphysical grammar of centralized control. Dismantling it philosophically is a precondition for building genuinely distributed systems.',
      tags: ['critique', 'philosophy', 'metaphysics', 'immanence'],
    },
    {
      id: 'symbolic_misery',
      label: 'Symbolic Misery',
      type: 'concept',
      cluster: 'critique',
      radius: 15,
      summary: 'Stiegler\'s diagnosis: hyperindustrial culture captures aisthēsis — collective sensory-aesthetic experience — reducing participants to consumers rather than co-creators of symbolic life.',
      whyItMatters: 'Symbolic misery is the aesthetic dimension of cognitive enclosure. It describes what television, advertising, and algorithmic media do to collective sensory life and participatory capacity.',
      tags: ['aesthetics', 'Stiegler', 'culture'],
    },

    // Movement II: Archive
    {
      id: 'archive',
      label: 'Investigation of the Archive',
      type: 'core',
      cluster: 'archive',
      radius: 22,
      summary: 'Historical protocol undergrounds as already-working proofs of concept for decentralized, consent-based, high-agency coordination without institutional authority.',
      whyItMatters: 'The underground is an empirical archive. These communities solved coordination problems institutions claim are unsolvable. Their protocols are recoverable and scalable.',
      tags: ['history', 'archive', 'counterculture', 'practice'],
    },
    {
      id: 'protocol_underground',
      label: 'Protocol Underground',
      type: 'tradition',
      cluster: 'archive',
      radius: 17,
      summary: 'Informal communities sustained by open protocols without institutional infrastructure: Brotherhood of Eternal Love (LSD), Spiral Tribe (free parties), Society of Janus (S/M consent culture).',
      whyItMatters: 'Each case solved coordination problems — pricing, trust, consent, collective action — through protocol design rather than institutional authority. The structural lessons are transferable.',
      tags: ['protocol', 'history', 'coordination', 'underground'],
    },
    {
      id: 'isomorphism',
      label: 'The Isomorphism Thesis',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Open-source software, blockchain systems, and cultural underground protocols share structural features: memeticism, empiricism, anti-capture design, distributed decision-making.',
      whyItMatters: 'The isomorphism thesis allows solutions to be imported across domains and grounds the claim that Web3 can \'overground\' underground practices without standardizing them.',
      tags: ['isomorphism', 'structure', 'protocol'],
    },
    {
      id: 'undercapital',
      label: 'Undercapital',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Economic activity grounded in the virtual dimension — felt possibility, affective force, the quality of presence that moves bodies and creates community coherence.',
      whyItMatters: 'Undercapital names what underground communities actually run on: depth of presence, affective charge, the sense of possibility. These are productive forces invisible to conventional economics.',
      tags: ['economics', 'virtual', 'Deleuze', 'affect'],
    },
    {
      id: 'cosmo_local',
      label: 'Cosmo-Local Practice',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: '\'What is heavy should be local; what is light should be global.\' Resilient local production connected to globally-shared knowledge commons.',
      whyItMatters: 'Cosmo-localism resolves the opposition between globalization and localism. Distributed place-based communities share protocols without standardization or homogenization.',
      tags: ['cosmo-localism', 'local', 'global', 'bioregion'],
    },
    {
      id: 'cogsec_strategies',
      label: "1960's & 70's CogSec Strategies",
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: "Cognitive security strategies developed in 1960s and 70s countercultural and activist contexts — techniques for protecting and cultivating epistemic autonomy against institutional capture.",
      whyItMatters: "These strategies represent an early, practical archive of methods for maintaining cognitive sovereignty under conditions of mass media saturation and psychological operations.",
      tags: ['history', 'cognition', 'sovereignty', 'counterculture'],
    },
    {
      id: 'lineage_immanence',
      label: 'The Lineage of Immanence',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'The historical thread of immanent philosophy — from Spinoza through Nietzsche, Bergson, Whitehead, and Deleuze — as an active intellectual archive recoverable for contemporary use.',
      whyItMatters: 'The lineage of immanence is not just history but a living protocol: a set of conceptual tools refined across centuries for thinking power, creativity, and agency without transcendence.',
      tags: ['history', 'philosophy', 'immanence', 'lineage'],
    },
    {
      id: 'extitutions',
      label: 'Extitutions',
      type: 'concept',
      cluster: 'archive',
      radius: 15,
      summary: 'Organizational forms that use institutional legibility while remaining committed to emergent values — structures that engage institutions without becoming them.',
      whyItMatters: 'Extitutions solve the navigation problem: how to operate in a world of institutions without capture. DAOs with dissolution clauses, indie labels that deliberately fail.',
      tags: ['organization', 'strategy', 'navigation'],
    },

    // Movement III: Construction
    {
      id: 'construction',
      label: 'The Construction of Immanent Technology',
      type: 'core',
      cluster: 'construction',
      radius: 22,
      summary: 'Building technical and conceptual infrastructure aligned with distributed agency, aesthetic co-creation, affirmative consent, process orientation, and open protocolization.',
      whyItMatters: 'Construction is not the opposite of critique but its completion. The three movements are sequential and mutually reinforcing.',
      tags: ['construction', 'design', 'technology', 'immanence'],
    },
    {
      id: 'diverse_intel',
      label: 'Diverse Intelligence Design',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Systems designed to recognize and coordinate with intelligence at all scales: cellular, collective, non-human, artificial — following Michael Levin\'s distributed cognition framework.',
      whyItMatters: 'Designing for diverse intelligence means building infrastructure that doesn\'t assume human-scale goal-directed cognition as the only valid form, opening coordination with ecosystems and swarms.',
      tags: ['intelligence', 'Levin', 'posthumanism', 'design'],
    },
    {
      id: 'open_protocol_infra',
      label: 'Open Protocol Infrastructure',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Ethereum, DAOs, retroactive public goods: formalization without standardization — minimum viable consensus through mathematics rather than institutional authority.',
      whyItMatters: 'Open protocol infrastructure is the technical means by which underground practices become legible and scalable without becoming capturable.',
      tags: ['Ethereum', 'DAOs', 'protocol', 'infrastructure'],
    },
    {
      id: 'immanent_criteria',
      label: 'Criteria for Immanent Technology',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'A five-point rubric: distributed agency, aesthetic co-creation, affirmative consent, process orientation, open protocolization.',
      whyItMatters: 'These criteria provide a practical decision procedure for evaluating whether a technology is aligned with immanent values. They are empirically derived from studying protocol undergrounds.',
      tags: ['criteria', 'evaluation', 'values', 'design'],
    },
    {
      id: 'nopunk',
      label: 'Noöpunk',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'An aesthetic-political movement seeing the universe as nested cognitive assemblages. A carnival of distributed minds activating through art, music, computation, and ecology.',
      whyItMatters: 'Noöpunk answers: what does it feel like to live inside an immanent world? It makes the project legible to people who arrive through culture rather than philosophy.',
      tags: ['aesthetics', 'art', 'culture', 'cognition'],
    },
    {
      id: 'cog_sovereignty',
      label: 'Cognitive Sovereignty',
      type: 'concept',
      cluster: 'construction',
      radius: 15,
      summary: 'Not just defense against cognitive enclosure but positive cultivation of direct interface with reality — epistemic autonomy that can discriminate between diverse intelligences and interfaces.',
      whyItMatters: 'Cognitive sovereignty completes the arc from critique to construction. Not isolation but discrimination; not impermeability but groundedness.',
      tags: ['sovereignty', 'cognition', 'autonomy'],
    },
  ],

  edges: [
    { source: 'open_machine', target: 'critique',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine', target: 'archive',             type: 'direct_influence',   weight: 2 },
    { source: 'open_machine', target: 'construction',        type: 'direct_influence',   weight: 2 },
    { source: 'critique',     target: 'moloch',              type: 'direct_influence',   weight: 1 },
    { source: 'critique',     target: 'enclosure',           type: 'direct_influence',   weight: 1 },
    { source: 'critique',     target: 'ontological_hierarchy', type: 'direct_influence', weight: 1 },
    { source: 'critique',     target: 'mind_blindness',      type: 'direct_influence',   weight: 1 },
    { source: 'critique',     target: 'symbolic_misery',     type: 'direct_influence',   weight: 1 },
    { source: 'critique',     target: 'critique_emanationism', type: 'direct_influence', weight: 1 },
    { source: 'archive',      target: 'protocol_underground', type: 'direct_influence',  weight: 1 },
    { source: 'archive',      target: 'isomorphism',         type: 'direct_influence',   weight: 1 },
    { source: 'archive',      target: 'undercapital',        type: 'direct_influence',   weight: 1 },
    { source: 'archive',      target: 'cosmo_local',         type: 'direct_influence',   weight: 1 },
    { source: 'archive',      target: 'extitutions',         type: 'direct_influence',   weight: 1 },
    { source: 'archive',      target: 'cogsec_strategies',   type: 'direct_influence',   weight: 1 },
    { source: 'archive',      target: 'lineage_immanence',   type: 'direct_influence',   weight: 1 },
    { source: 'construction', target: 'diverse_intel',       type: 'direct_influence',   weight: 1 },
    { source: 'construction', target: 'open_protocol_infra', type: 'direct_influence',   weight: 1 },
    { source: 'construction', target: 'immanent_criteria',   type: 'direct_influence',   weight: 1 },
    { source: 'construction', target: 'nopunk',              type: 'direct_influence',   weight: 1 },
    { source: 'construction', target: 'cog_sovereignty',     type: 'direct_influence',   weight: 1 },
    { source: 'critique',     target: 'archive',             type: 'conceptual_affinity', weight: 2 },
    { source: 'archive',      target: 'construction',        type: 'applied_extension',  weight: 2 },
    { source: 'moloch',       target: 'enclosure',           type: 'conceptual_affinity', weight: 1 },
    { source: 'protocol_underground', target: 'extitutions', type: 'conceptual_affinity', weight: 1 },
    { source: 'isomorphism',  target: 'open_protocol_infra', type: 'applied_extension',  weight: 2 },
    { source: 'undercapital', target: 'immanent_criteria',   type: 'applied_extension',  weight: 1 },
    { source: 'symbolic_misery', target: 'nopunk',           type: 'applied_extension',  weight: 2 },
    { source: 'mind_blindness',  target: 'diverse_intel',    type: 'applied_extension',  weight: 2 },
    { source: 'enclosure',    target: 'cog_sovereignty',     type: 'applied_extension',  weight: 2 },
  ],
}

// ─── VISION 3 ────────────────────────────────────────────────────────────────

export const VISION_3 = {
  nodes: [
    {
      id: 'open_machine',
      label: 'Open Machine',
      type: 'open_machine',
      cluster: 'core',
      radius: 28,
      layer: 3,
      summary: 'A research and practice collective synthesizing immanent philosophy with emerging technology.',
      whyItMatters: 'The Open Machine inhabits all three movements simultaneously: diagnosing transcendent control structures, recovering protocol underground archives, and building immanent technological infrastructure.',
      tags: ['research', 'collective', 'immanence', 'protocol'],
    },

    // Layer 5 — Aesthetics & Phenomenology
    {
      id: 'layer5',
      label: 'Aesthetics & Phenomenology',
      type: 'core',
      cluster: 'aesthetics',
      radius: 22,
      layer: 5,
      summary: 'The fabric of collective sensory-cognitive life; how reality is felt and made as much as known.',
      whyItMatters: 'Aesthetics in the Stieglerian sense (aisthēsis) is the most fundamental layer — it shapes what can be perceived and experienced before any epistemology or coordination is possible.',
      tags: ['aesthetics', 'phenomenology', 'experience'],
    },
    {
      id: 'nopunk_l5',
      label: 'Noöpunk',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'The aesthetic-political movement seeing the universe as nested cognitive assemblages activating through art, music, computation, and ecology.',
      whyItMatters: 'Noöpunk is the felt practice of the entire stack — what living inside an immanent world looks and feels like.',
      tags: ['art', 'culture', 'cognition'],
    },
    {
      id: 'symbolic_commons',
      label: 'Symbolic Commons',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'Shared aesthetic and symbolic resources held in common — music, imagery, language, narrative — that enable collective sense-making outside market mediation.',
      whyItMatters: 'The symbolic commons is what cognitive enclosure destroys and what protocol undergrounds rebuild. It is the aesthetic infrastructure of community.',
      tags: ['commons', 'aesthetics', 'culture'],
    },
    {
      id: 'aisthesis',
      label: 'Aisthēsis',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'The pre-cognitive, bodily dimension of perception and sensory experience — what Stiegler identifies as the primary site of political-aesthetic contestation.',
      whyItMatters: 'Aisthēsis is why advertising and algorithmic media are more than annoyances — they restructure the perceptual substrate of collective life before thought begins.',
      tags: ['Stiegler', 'perception', 'politics'],
    },
    {
      id: 'technedelics_l5',
      label: 'Technedelics',
      type: 'concept',
      cluster: 'aesthetics',
      radius: 15,
      layer: 5,
      summary: 'Technologies and practices (psychedelics, VR, deep media) that enable encounter with radically foreign umwelts — alien sensory-cognitive worlds.',
      whyItMatters: 'Technedelics sit at the intersection of aesthetics and epistemology: they are the most radical form of perceptual expansion, testing the limits of what can be experienced and known.',
      tags: ['psychedelics', 'umwelt', 'experience'],
    },

    // Layer 4 — Coordination & Governance
    {
      id: 'layer4',
      label: 'Coordination & Governance',
      type: 'core',
      cluster: 'coordination',
      radius: 22,
      layer: 4,
      summary: 'How distributed agents act together without surrendering agency to a center — stigmergy, polycentric governance, consent culture, cosmo-local networks.',
      whyItMatters: 'Coordination is where ontology meets practice. The question is not whether to coordinate but on what terms — and with what relationship to diverse intelligences and open protocols.',
      tags: ['coordination', 'governance', 'collective'],
    },
    {
      id: 'cosmo_local_l4',
      label: 'Cosmo-Localism',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Heavy things local, light things global. Resilient bioregional production networked to shared knowledge commons.',
      whyItMatters: 'Cosmo-localism is the operational synthesis of the entire project — how to be rooted and connected without being isolated or homogenized.',
      tags: ['cosmo-localism', 'local', 'global'],
    },
    {
      id: 'stigmergy',
      label: 'Stigmergy',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Swarm coordination without central planning — agents signal through environmental modification, enabling positive-sum feedback loops (ants, Wikipedia, Burning Man).',
      whyItMatters: 'Stigmergy proves that complex collective coordination doesn\'t require hierarchy or central authority. It is the coordination mechanism of the protocol underground.',
      tags: ['swarm', 'emergence', 'coordination'],
    },
    {
      id: 'polycentric',
      label: 'Polycentric Governance',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Multiple overlapping scales of governance, each handling what is appropriate to its level — Ostrom\'s principle of subsidiarity applied to information and resource commons.',
      whyItMatters: 'Polycentric governance is how cosmo-localism gets operationalized institutionally: neither global monoculture nor local fragmentation but nested, overlapping jurisdictions.',
      tags: ['Ostrom', 'commons', 'governance'],
    },
    {
      id: 'consent_culture',
      label: 'Consent Culture',
      type: 'tradition',
      cluster: 'coordination',
      radius: 17,
      layer: 4,
      summary: 'The S/M community\'s development of explicit, ongoing, renegotiable consent as a full coordination protocol — now recoverable for broader social design.',
      whyItMatters: 'Consent culture is the protocol underground\'s answer to how you coordinate intimately without coercion. It is a working proof of concept for affirmative consent as governance principle.',
      tags: ['consent', 'protocol', 'ethics', 'history'],
    },
    {
      id: 'semiotic_bridging',
      label: 'Semiotic Bridging',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'Revealing underlying compatibility between diverse movements and frameworks by translating between their distinct vocabularies without demanding ideological unity.',
      whyItMatters: 'Semiotic bridging is how cosmo-local coalitions are built. It is the communicative practice that allows diverse communities to coordinate without standardizing.',
      tags: ['communication', 'translation', 'coalition'],
    },

    // Layer 3 — Infrastructure
    {
      id: 'layer3',
      label: 'Infrastructure',
      type: 'core',
      cluster: 'infrastructure',
      radius: 22,
      layer: 3,
      summary: 'The formal substrate that makes coordination legible without making it capturable — open protocols, cryptographic consensus, distributed compute.',
      whyItMatters: 'Infrastructure is the layer that either enables or forecloses all layers above it. Open infrastructure is the technical precondition for immanent governance and aesthetics.',
      tags: ['infrastructure', 'protocol', 'technical'],
    },
    {
      id: 'ethereum',
      label: 'Ethereum',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Ontologically agnostic distributed compute infrastructure — capable of treating diverse forms of intelligence and agency symmetrically, without reference to human sovereignty.',
      whyItMatters: 'Ethereum is posthuman infrastructure: it provides formalization without standardization, minimum viable consensus through mathematics rather than institutional authority.',
      tags: ['Ethereum', 'blockchain', 'posthumanism'],
    },
    {
      id: 'open_protocols',
      label: 'Open Protocols',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Memetic, empirical, anti-capture protocol design — reproducible, forkable, adaptable to local context without losing coherence.',
      whyItMatters: 'Open protocols are the formalization without standardization that allows underground practices to scale. They are the technical instantiation of the isomorphism thesis.',
      tags: ['protocol', 'open-source', 'design'],
    },
    {
      id: 'daos',
      label: 'DAOs',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Decentralized autonomous organizations: smart-contract-based coordination mechanisms that formalize governance without requiring institutional authority.',
      whyItMatters: 'DAOs are the organizational form corresponding to extitutional strategy — they use institutional legibility (legal wrappers) while remaining operationally committed to distributed governance.',
      tags: ['DAOs', 'governance', 'smart-contracts'],
    },
    {
      id: 'mycofi',
      label: 'MycoFi',
      type: 'concept',
      cluster: 'infrastructure',
      radius: 15,
      layer: 3,
      summary: 'Fungal network models applied to distributed resource allocation — the mycelium as both metaphor and template for peer-to-peer economic coordination.',
      whyItMatters: 'MycoFi extends cosmo-localism into regenerative economics, proposing that resource flows can be organized according to ecological rather than market logics.',
      tags: ['ecology', 'economics', 'distributed'],
    },

    // Layer 2 — Epistemology & Cognition
    {
      id: 'layer2',
      label: 'Epistemology & Cognition',
      type: 'core',
      cluster: 'epistemology',
      radius: 22,
      layer: 2,
      summary: 'What counts as knowing, who counts as a knower, and who controls the conditions of perception — the contested layer of diverse intelligence and cognitive sovereignty.',
      whyItMatters: 'Epistemology is where the philosophical and the political converge: controlling how we know is controlling how we can act and what we can coordinate with.',
      tags: ['epistemology', 'cognition', 'sovereignty'],
    },
    {
      id: 'diverse_intel_l2',
      label: 'Diverse Intelligence',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Michael Levin\'s framework: intelligence as distributed across nested problem-solving systems — cells in metabolic space, organisms in physical space, collectives in social space.',
      whyItMatters: 'Diverse intelligence expands the roster of cognitive agents we can coordinate with, and provides the epistemological ground for posthumanist infrastructure design.',
      tags: ['Levin', 'intelligence', 'cognition'],
    },
    {
      id: 'cog_sovereignty_l2',
      label: 'Cognitive Sovereignty',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Freedom from institutional determination of thought and perception — the positive capacity to appraise and engage diverse intelligences from a position of epistemic autonomy.',
      whyItMatters: 'Cognitive sovereignty is the personal and collective counterpart to open protocol infrastructure: it is what free infrastructure enables and what cognitive enclosure destroys.',
      tags: ['sovereignty', 'autonomy', 'cognition'],
    },
    {
      id: 'umwelt',
      label: 'Umwelt',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Jakob von Uexküll\'s concept: each organism inhabits a unique perceptual world defined by its sensory apparatus and cognitive capacities. Encountering alien umwelts expands epistemic space.',
      whyItMatters: 'Umwelt thinking is the perceptual foundation of diverse intelligence: to recognize other minds, you must be able to conceive that other perceptual worlds exist and are real.',
      tags: ['umwelt', 'perception', 'biology'],
    },
    {
      id: 'dist_cognition',
      label: 'Distributed Cognition',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Edward Hutchins\' framework: cognitive processes extend beyond individual minds into socio-technical systems. Ships navigate, teams problem-solve, cities remember.',
      whyItMatters: 'Distributed cognition grounds the stigmergy claim: collective intelligence is not metaphorical but literally cognitive — the system knows things no individual knows.',
      tags: ['Hutchins', 'cognition', 'systems'],
    },
    {
      id: 'technedelics_l2',
      label: 'Technedelics (Epistemic)',
      type: 'concept',
      cluster: 'epistemology',
      radius: 15,
      layer: 2,
      summary: 'Psychedelics and radical media as epistemological tools: empirical access to alien umwelts, direct test of the limits of cognitive sovereignty.',
      whyItMatters: 'From the epistemological layer, technedelics are less about experience and more about what they prove: that other cognitive worlds are real and accessible, and that the sovereign observer is a construction.',
      tags: ['psychedelics', 'epistemology', 'umwelt'],
    },

    // Layer 1 — Ontology
    {
      id: 'layer1',
      label: 'Ontology',
      type: 'core',
      cluster: 'ontology',
      radius: 22,
      layer: 1,
      summary: 'What is real; what kinds of agency exist; what is the nature of creative emergence — the philosophical ground of the entire stack.',
      whyItMatters: 'Ontology is not the most abstract layer but the most fundamental. Every design decision about infrastructure, governance, and aesthetics encodes ontological assumptions. Making them explicit is the work of layer 1.',
      tags: ['ontology', 'philosophy', 'metaphysics'],
    },
    {
      id: 'immanence',
      label: 'Immanence',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Deleuzian concept: creative capacity arising from relational fields without central command. Power distributed within, not emanating from above. Against transcendence in all its forms.',
      whyItMatters: 'Immanence is the unifying philosophical principle of the entire project. It names what the three movements and five layers are all, in their different registers, trying to instantiate.',
      tags: ['Deleuze', 'immanence', 'philosophy'],
    },
    {
      id: 'the_virtual',
      label: 'The Virtual',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Deleuze\'s reading of Bergson: the virtual is real but not actual — the generative field of potentiality that animates material processes without being directly quantifiable.',
      whyItMatters: 'The virtual is why undercapital is real economics, why the underground matters, why aesthetic experience is productive. It names the dimension that institutional accounting cannot see.',
      tags: ['Deleuze', 'Bergson', 'virtual', 'potentiality'],
    },
    {
      id: 'undercapital_l1',
      label: 'Undercapital',
      type: 'concept',
      cluster: 'coordination',
      radius: 15,
      layer: 4,
      summary: 'The ontological claim behind the economic concept: that the virtual dimension is a real productive force, and that organizing to access it generates genuine value.',
      whyItMatters: 'Undercapital at the coordination layer is the claim that the felt sense of possibility is not epiphenomenal but causal — that presence, trust, and affective charge are primary economic facts.',
      tags: ['economics', 'virtual', 'coordination'],
    },
    {
      id: 'open_ended',
      label: 'Open-Ended Intelligence',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Weinbaum & Veitas: intelligence as distributed, self-reflexive, and without terminal state — the rejection of goal-optimization for open-ended adaptive becoming.',
      whyItMatters: 'Open-ended intelligence is the ontological basis for diverse intelligence: if intelligence has no fixed goal, it cannot be defined by its output but only by its processual character.',
      tags: ['intelligence', 'AI', 'becoming'],
    },
    {
      id: 'posthumanism',
      label: 'Posthumanism',
      type: 'concept',
      cluster: 'ontology',
      radius: 15,
      layer: 1,
      summary: 'Rejection of the autonomous sovereign subject as the primary unit of moral and political consideration — distributed agency at all scales, from cells to collectives.',
      whyItMatters: 'Posthumanism is the ontological foundation for Ethereum\'s technical design (no reference to human sovereignty), for diverse intelligence research, and for bioregional governance.',
      tags: ['posthumanism', 'agency', 'subject'],
    },
  ],

  edges: [
    { source: 'open_machine',      target: 'layer5',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer4',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer3',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer2',            type: 'direct_influence',   weight: 2 },
    { source: 'open_machine',      target: 'layer1',            type: 'direct_influence',   weight: 2 },
    { source: 'layer5',            target: 'nopunk_l5',         type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'symbolic_commons',  type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'aisthesis',         type: 'direct_influence',   weight: 1 },
    { source: 'layer5',            target: 'technedelics_l5',   type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'cosmo_local_l4',    type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'stigmergy',         type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'polycentric',       type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'consent_culture',   type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'semiotic_bridging', type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'ethereum',          type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'open_protocols',    type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'daos',              type: 'direct_influence',   weight: 1 },
    { source: 'layer3',            target: 'mycofi',            type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'diverse_intel_l2',  type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'cog_sovereignty_l2', type: 'direct_influence',  weight: 1 },
    { source: 'layer2',            target: 'umwelt',            type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'dist_cognition',    type: 'direct_influence',   weight: 1 },
    { source: 'layer2',            target: 'technedelics_l2',   type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'immanence',         type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'the_virtual',       type: 'direct_influence',   weight: 1 },
    { source: 'layer4',            target: 'undercapital_l1',   type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'open_ended',        type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'posthumanism',      type: 'direct_influence',   weight: 1 },
    { source: 'layer1',            target: 'layer2',            type: 'applied_extension',  weight: 3 },
    { source: 'layer2',            target: 'layer3',            type: 'applied_extension',  weight: 3 },
    { source: 'layer3',            target: 'layer4',            type: 'applied_extension',  weight: 3 },
    { source: 'layer4',            target: 'layer5',            type: 'applied_extension',  weight: 3 },
    { source: 'immanence',         target: 'diverse_intel_l2',  type: 'conceptual_affinity', weight: 2 },
    { source: 'the_virtual',       target: 'undercapital_l1',   type: 'conceptual_affinity', weight: 2 },
    { source: 'open_ended',        target: 'diverse_intel_l2',  type: 'conceptual_affinity', weight: 2 },
    { source: 'posthumanism',      target: 'ethereum',          type: 'applied_extension',  weight: 2 },
    { source: 'umwelt',            target: 'technedelics_l5',   type: 'conceptual_affinity', weight: 2 },
    { source: 'stigmergy',         target: 'open_protocols',    type: 'conceptual_affinity', weight: 2 },
    { source: 'consent_culture',   target: 'daos',              type: 'applied_extension',  weight: 2 },
    { source: 'cosmo_local_l4',    target: 'mycofi',            type: 'conceptual_affinity', weight: 1 },
    { source: 'aisthesis',         target: 'symbolic_commons',  type: 'conceptual_affinity', weight: 1 },
    { source: 'dist_cognition',    target: 'stigmergy',         type: 'conceptual_affinity', weight: 2 },
    { source: 'technedelics_l2',   target: 'technedelics_l5',   type: 'conceptual_affinity', weight: 1 },
  ],
}
